### ISSUE TITLE
Error building patron

### ISSUE THREAD

**Issue by liamwhite** [oracle/truffleruby#1087]
```
$ gem install patron
Fetching: patron-0.12.0.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing patron:
	ERROR: Failed to build gem native extension.

    current directory: /opt/graalvm-0.31/jre/languages/ruby/lib/ruby/gems/2.3.0/gems/patron-0.12.0/ext/patron
/opt/graalvm-0.31/jre/languages/ruby/bin/truffleruby -r ./siteconf20180208-12603-1ytd701.rb extconf.rb
checking for curl-config... yes
checking for ruby/thread.h... yes
checking for rb_thread_blocking_region() in ruby.h... no
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /opt/graalvm-0.31/jre/languages/ruby/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/patron-0.12.0/mkmf.log

current directory: /opt/graalvm-0.31/jre/languages/ruby/lib/ruby/gems/2.3.0/gems/patron-0.12.0/ext/patron
make "DESTDIR=" clean

current directory: /opt/graalvm-0.31/jre/languages/ruby/lib/ruby/gems/2.3.0/gems/patron-0.12.0/ext/patron
make "DESTDIR="
compiling membuffer.c
compiling session_ext.c
session_ext.c:14:24: error: initializer element is not a compile-time constant
static VALUE mPatron = Qnil;
                       ^~~~
/opt/graalvm-0.31/jre/languages/ruby/lib/cext/ruby/ruby.h:439:14: note: expanded from macro 'Qnil'
#define Qnil rb_tr_get_nil()
             ^~~~~~~~~~~~~~~
session_ext.c:15:27: error: initializer element is not a compile-time constant
static VALUE mProxyType = Qnil;
                          ^~~~
/opt/graalvm-0.31/jre/languages/ruby/lib/cext/ruby/ruby.h:439:14: note: expanded from macro 'Qnil'
#define Qnil rb_tr_get_nil()
             ^~~~~~~~~~~~~~~
```
(several more of the same error follow)

Possible solutions:
1. patron needs an ad-hoc patch to fix the behavior (per cext/preprocess.rb)
2. `Qnil` needs to be a static value instead of a function call
3. The value assignments need to be copied into global constructors, a la C++
4. Something else?

**Comment by chrisseaton** [comment]
Hello, thanks for the report.

We are still finding solutions to some problems with the native/managed hybrid execution model that we use for C extensions. This particular problem is documented here.

https://github.com/oracle/truffleruby/blob/d8b56960c6293f7152e3ec0da646c8fcc58a42a3/doc/user/compatibility.md#identifiers-may-be-macros-or-functions

It talks about 'a workaround' but that's our working thinking, not what we would recommend anyone actually change in their source code. We'd normally like to patch this in the preprocessor, you are right, but because it's a non-local thing (move a static initialiser into an `Init_` function) it's not easy to do.

Do you want to just casually experiment with this gem, or does fixing it enable you to try something more interesting that you'd really like to try.

I could simply tell you 'this gem isn't supported yet', or we can work with you to patch it manually to get it working for whatever you want to try next.

**Comment by chrisseaton** [comment]
Source code line in question:

https://github.com/toland/patron/blob/25777074c6efab21d5b23a4995b8ea67174d48ab/ext/patron/session_ext.c#L14

**Comment by chrisseaton** [comment]
The rest of this C extension looks on a casual glance to be fairly compatible with how we execute C extensions.

**Comment by liamwhite** [comment]
While I do not need the Patron gem in order to run the code I am interested in running, I was instructed to report this bug. I was not aware this was already a known issue; should I close this bug report?

**Comment by chrisseaton** [comment]
No I’ll see if I can patch it and get it running - it’s good to try on gems I haven’t looked at before.

**Comment by eregon** [comment]
I fixed assigning `Qnil` in C global variables since 1.0.0-rc3, that now works and `gem install patron` builds and succeeds.
I don't know if the tests pass, but since this issue is about failing the build, that part is resolved.
