### ISSUE TITLE
Recursive factorial is faster in MRI and JRuby

### ISSUE THREAD

**Issue by Papierkorb** [oracle/truffleruby#1392]
Hello,

I ran the following benchmark on my machine:

```ruby
require 'benchmark/ips'

def f(x)
  if x > 1
    x * f(x - 1)
  else
    x
  end
end

Benchmark.ips do |x|
  x.iterations = 3
  x.report('factorial'){ f(1_000) }
end
```
**JRuby** did best:
```
Warming up --------------------------------------
           factorial   431.000  i/100ms
           factorial   527.000  i/100ms
           factorial   546.000  i/100ms
Calculating -------------------------------------
           factorial      5.607k (± 4.2%) i/s -     28.392k in   5.073286s
           factorial      5.626k (± 3.6%) i/s -     28.392k in   5.053876s
           factorial      5.687k (± 2.4%) i/s -     28.938k in   5.091859s
```

**MRI** isn't super fast – It was never really good at recursive algorithms:
```
Warming up --------------------------------------
           factorial   260.000  i/100ms
           factorial   267.000  i/100ms
           factorial   267.000  i/100ms
Calculating -------------------------------------
           factorial      2.714k (± 1.6%) i/s -     13.617k in   5.019048s
           factorial      2.714k (± 2.4%) i/s -     13.617k in   5.020505s
           factorial      2.747k (± 0.6%) i/s -     13.884k in   5.055003s
```

However, **TruffleRuby** did worse than **MRI**:
```
Warming up --------------------------------------
           factorial   196.000  i/100ms
           factorial   204.000  i/100ms
           factorial   205.000  i/100ms
Calculating -------------------------------------
           factorial      2.089k (±14.9%) i/s -     10.250k in   5.059807s
           factorial      2.100k (±15.1%) i/s -     10.250k in   5.038273s
           factorial      2.101k (±15.1%) i/s -     10.250k in   5.034718s
```

I tried passing the `--jvm` flag to `truffleruby`, but that ended up with throwing a stack overflow exception.  The invocation used was simply `truffleruby factorial.rb`.

Versions:
```
jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 OpenJDK 64-Bit Server VM 25.172-b11 on 1.8.0_172-b11 +jit [linux-x86_64]
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
truffleruby 1.0.0-rc3, like ruby 2.4.4, GraalVM CE Native [x86_64-linux]
```

Cheers!

**Comment by eregon** [comment]
@Papierkorb The default stack size on JVM seems too small to recurse 1000 times in Ruby.
Note that you can increase the stack size in JVM with `-J-Xss`:
```
ruby --jvm -J-Xss4m bench.rb
```
Could you post your results with this additional option?
For me, this is then faster than MRI with GraalVM 1.0.0-rc3:
~3.5k `--jvm` vs ~2.2k `MRI 2.5.1` vs ~1.7k `--native`.

**Comment by eregon** [comment]
It goes without saying, but such a benchmark is of course not very representative of what people do in Ruby. Recursion is rarely used, and potentially unbounded recursion like this leads to stack overflow with large inputs as there is no tail recursion (by default) in Ruby.

But I guess it's somewhat interesting to get an idea of non-inlined call overhead, although some inlining can still happen for recursive functions. This benchmark also depends on Bignum performance.

**Comment by Papierkorb** [comment]
Sorry for the delay, was absent from home.  With your call @eregon it now runs through, putting it into second place:

```
Warming up --------------------------------------
           factorial   305.000  i/100ms
           factorial   416.000  i/100ms
           factorial   444.000  i/100ms
Calculating -------------------------------------
           factorial      4.507k (± 3.6%) i/s -     22.644k in   5.030648s
           factorial      4.500k (± 4.5%) i/s -     22.644k in   5.042733s
           factorial      4.539k (± 3.6%) i/s -     23.088k in   5.093634s
```

It is correct that ruby code rarely uses recursive algorithms.  But I think this is also for the historical reason that MRI simply didn't perform well in these.  And second, I was curious if TruffleRuby supported Tail-Call Recursion.  I couldn't tell you how often I'd actually write such a function in the wild, especially as I too always tried avoid recursive functions if possible.

**Comment by eregon** [comment]
@Papierkorb Thank you for the numbers. It is slightly surprising to me that the JVM is much faster (2x) on this benchmark, as I would think call overhead is about the same on SubstateVM. Maybe runtime profiling of BigInteger operations helps the JVM.

TruffleRuby doesn't support tail-call optimization at the moment.
It is probably something we could implement, as tail-call optimization works in [Mozart-Graal](https://github.com/eregon/mozart-graal/blob/master/vm/src/org/mozartoz/truffle/nodes/call/TailCallCatcherNode.java), another Truffle interpreter.
However, I think enabling the tail-call optimization for all calls in tail position would add an overhead and might lose backtrace entries unintentionally. I think the latter reason is the main reason why the tail-call optimization is not enabled by default in MRI.
[Self recursion](https://github.com/eregon/mozart-graal/blob/master/vm/src/org/mozartoz/truffle/nodes/call/SelfTailCallCatcherNode.java) on the other hand seems to have almost no overhead (once compiled) and the concern about the backtrace is less important since it's all invocations of the same method at the top of the stack (so the lost entries are the same as the top frame, except maybe the line number).

@Papierkorb Do you have (an) example(s) of typical recursive functions/methods you write or see in Ruby? Are they self-recursive?

**Comment by Papierkorb** [comment]
Regarding your point on the backtrace, yes this is an issue, and also why I only expected this optimization on self-recursion.

A (typically) not self-recursive use-case is to handle recursive data structures:

1. Handling (recursive) data structures (Including JSON documents)
2. Routing of (Web) requests to the handler function ([Roda](http://roda.jeremyevans.net/index.html) works like this)
3. Helper functions like deep-`#freeze`ing an object tree (Depth-first algorithm to re-construct a tree of only frozen objects).  A structurally equivalent algorithm is used to deep-`#clone` an object tree.

Self-recursive methods are rare in Ruby, as mentioned, also because MRI was never that good at it.  I can't even come up with a use-case as far existing ruby code goes.  But that aside, it could speed up math algorithms, which were written as C extension before.

**Comment by eregon** [comment]
@Papierkorb I think tail calls cannot be used for visiting/iterating/transforming most recursive non-linear data structures (if there can be multiple elements to visit from the previous element), as only the last call can be tail:
```ruby
def visit(binary_tree)
  if binary_tree.is_a?(Leaf)
    ...
  else
    visit(binary_tree.left)  # not tail call
    visit(binary_tree.right) # tail call
  end
end
```
So I think using tail calls wouldn't work for JSON, Roda or deep-freezing an object graph, because at least one call is not tail, and therefore recursion is limited by the stack size (maximum number of stack frames).

> But that aside, it could speed up math algorithms, which were written as C extension before.

These math algorithms could be rewritten without recursion, and likely would be far more efficient without recursion, both in Ruby and C :smiley: 

Given that there doesn't seem to be a real use-case for self-tail-call optimization so far, and general TCO would mess the backtrace, I would like to close this issue. If someone is interested, please post examples of what you would like to achieve with recursion in Ruby, and why TCO is needed for that use-case.
