### ISSUE TITLE
Referencing jar class in Ruby

### ISSUE THREAD

**Issue by zaknuces** [oracle/truffleruby#1603]
Hi, I am new to TruffleRuby and Graal. I am trying to use a Java SDK in ruby. However, I am having a hard time referencing the classes in the SDK jar. I am doing the following:

ruby --jvm --jvm.classpath=messaging-jar-with-dependencies.jar --polyglot example.rb 

In the example.rb, I am doing the following:

Commons = Java.type('myorg.util.Commons')
puts Commons.SDK_VERSION

Error
example.rb:7:in `<main>': Unknown identifier: SDK_VERSION (NoMethodError)

**Comment by chrisseaton** [comment]
Thanks for the report. Our Java Interop is not compatible with JRuby's. This is because instead of just bridging Ruby and Java, we're bridging any language with any other language.

The specific answer to your question is here https://github.com/oracle/truffleruby/blob/f6b387c4e239dec178094b4247cf4a3c5bc3b04f/doc/user/jruby-migration.md#referring-to-constants.

> In JRuby, Java constants are modelled as Ruby constants, `MyClass::FOO`. In TruffleRuby you use the read notation to read them as a property, `MyClass[:FOO]`.

I can explain a bit more about why that is if you're interested, but basically we have a basic JavaScript-style object as our interop model, and constants are modelled as properties that you can read. Ruby's method call syntax is reserved (mainly) for actual method calls.
