### ISSUE TITLE
Patching eventmachine like nokogiri for working in TruffleRuby

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1675]
Hello,
it seems eventmachine's developers are not too much flexible to patch eventmachine + the @eregon  patch is for future 1.3. That doesn't solve many problems with a dependency on 1.2 which is here for long time. So I think TruffleRuby would patch eventmachine while compiling for a while.

**Comment by eregon** [comment]
Related issues for compilation errors (fixed with the PR): #1597 #1541
Merged PR for EventMachine: https://github.com/eventmachine/eventmachine/pull/878

#1623 is something we need to address in any case before it works at all.

@deepj 
> it seems eventmachine's developers are not too much flexible to patch eventmachine + the @eregon patch is for future 1.3.

Why do you think so? Did you ask them directly?
I think we should ask them again for a release.

> That doesn't solve many problems with a dependency on 1.2 which is here for long time.

Maybe we could ask them for a release using the latest 1.2.x + my PR, if the concern is many Gemfiles lock to `eventmachine 1.2`. In general, it still seems a good idea to update gems before running on TruffleRuby, it's just going to work better.

> So I think TruffleRuby would patch eventmachine while compiling for a while.

It seems really not easy in this case, since `extconf.rb` needs to be modified to compile and the 2 `extconf.rb` are fairly long files.
Currently, we have the ability to patch C extension `.c` files (with search/replace), and `require`-d files from stdlib and gems (we load our patch instead of the original file, with the possibility to still load the orignal file).
`extconf.rb` is not `require`-d so that would need special handling, and since we wouldn't want to replicate a lot of logic we'd want some kind of search/replace patching.

My opinion is we should avoid patching as much as possible, it's too high of a cost from past experience.

**Comment by deepj** [comment]
@eregon this is a just idea. I've just met with many things depending on EventMachine 1.2 series. E.g. many things around ActionCable depends on this. Not only. Thin server uses it in the background.

> Why do you think so? Did you ask them directly?

No, just intuition. The last release was May 2018. But yes, it would be much better to ask them if they could make a release.

**Comment by eregon** [comment]
OK, I will ask for a release again on that PR once we have fixed #1623 or made sure it's something we can solve in TruffleRuby without upstream modifications.

**Comment by deepj** [comment]
@eregon I agree with your statement, the patching is not good. I'm just feeling this is a big pain after Nokogiri. If you'd be a chance to release EventMachine 1.2.8 with TruffleRuby support, then it changes the game. I believe, this would be the best scenario to release a special version supporting TruffleRuby.

**Comment by eregon** [comment]
With recent changes mentioned in https://github.com/oracle/truffleruby/issues/1541#issuecomment-601827420, eventmachine 1.2.7 can be installed and doesn't need any patching.
