### ISSUE TITLE
StackOverFlow error when naming a top level function 'hash'

### ISSUE THREAD

**Issue by Confusion** [oracle/truffleruby#1699]
TruffleRuby 19.0.0, JDK 11.0.3

The following code fails with a StackOverflowError
```
def hash
  [[1, 1], ['a', 'a']].to_h
end

puts hash['whatever']
```

Output:
```
$ truffleruby hangs.rb
[ruby] WARNING StackOverflowError
[ruby] WARNING StackOverflowError
hangs.rb:2:in `to_h': stack level too deep (SystemStackError)
	from StackOverflowCheckImpl.java:371:in `com.oracle.svm.core.graal.snippets.StackOverflowCheckSnippets.newStackOverflowError0'
	from hangs.rb:2:in `hash'
	from hangs.rb:2:in `[]='
	from hangs.rb:2:in `block in to_h'
	from hangs.rb:2:in `each_with_index'
	from hangs.rb:2:in `to_h'
	from hangs.rb:2:in `hash'
        [ snipped repetitions ] 
```

**Comment by chrisseaton** [comment]
When you define `#hash` at the top level you are redefining it for `Object`. That's going to break a lot of things in standard Ruby as well. For example.

```ruby
def hash
  raise
end

{Object.new => 14}
```

```
Traceback (most recent call last):
	1: from test.rb:5:in `<main>'
test.rb:2:in `hash': unhandled exception
```

It just breaks more quickly for TruffleRuby, because we implement the core library in Ruby itself. You will get exactly the same error for your code on Rubinius, and running anything more would also break MRI and JRuby.

I'm not sure I'd call this a bug. You're monkey patching the core library.

What do you think?

**Comment by Confusion** [comment]
I agree. And I should have checked the same script with MRI.

I'd never realized/discovered the top level redefined methods on Object. Pry, irb etc. define their own top-level, so you don't often run into it.
