### ISSUE TITLE
Upgrade stdlib from 2.6.2 to 2.6.5

### ISSUE THREAD

**Issue by nirvdrum** [oracle/truffleruby#1749]
I'm getting started with a new Rails project and the mismatch between TruffleRuby's latest stdlib version and MRI's is a bit annoying. This is because the generated Gemfile from `rails new` adds a `ruby` version directive. Since the latest TruffleRuby and MRI have different reported stdlib versions, I can't readily share the Gemfile between the two implementations. The directive is optional, so for now I've just removed it. However, it would be a better out-of-the-box experience Rails experience if I didn't need to do that.

**Comment by eregon** [comment]
We plan to upgrade to 2.6.4 although I'm not sure yet when it will land. One of the other reasons is to restore `rdoc` support now that the [related vulnerability](https://www.ruby-lang.org/en/news/2019/08/28/multiple-jquery-vulnerabilities-in-rdoc/) has been fixed upstream.

Note however that using the same Gemfile for both MRI and TruffleRuby might not always work.
For instance, `rails new` generates a different Gemfile on MRI on Rails 5 & 6 IIRC (adding MRI-specific gems like for debugging only if `rails new` ran on MRI).
I think we should fix that in Rails by using Bundler `platforms`, so it's the same Gemfile generated for both MRI and TruffleRuby.

Another thing is MRI 2.6.4 has a [severe String corruption bug](https://bugs.ruby-lang.org/issues/16136), so that might cause people to stay on 2.6.3 until 2.6.5 is released with the fix.

**Comment by nirvdrum** [comment]
Thanks. I'm fairly well aware of the issues with trying to share the Gemfile. I probably wouldn't have even tried MRI if I hadn't run into #1750. Thanks for the info on the String corruption bug, though. I hadn't seen that.

**Comment by eregon** [comment]
Indeed, we're currently planning to update to 2.6.5. I updated the issue title as well.

**Comment by eregon** [comment]
We updated to Ruby 2.6.5 in https://github.com/oracle/truffleruby/commit/9b8b8579e86673b5d3e62e08836ee71ebca21af5 and restored the RDoc template files.
