### ISSUE TITLE
jt.rb can no longer auto-install a JVMCI build.

### ISSUE THREAD

**Issue by nirvdrum** [oracle/truffleruby#1755]
Rev. b382d3b958bda063fa3fb87b91ca37cf223868c2 removed the "openjdk" reference from ci.jsonnet, which now causes the [version lookup mechanism](https://github.com/oracle/truffleruby/blob/79fa32e7fa65dc967f4cd24ed72eb73c5560b392/tool/jt.rb#L138) in jt.rb to fail. There's no "openjdk" reference to match. Simply changing it to "oraclejdk" doesn't work either, unfortunately, because the Oracle JDK version numbers don't match the OpenJDK ones.

The workaround for the time being is to either manually install a JVMCI build or set the `JVMCI_VERSION` environment variable.

**Comment by nirvdrum** [comment]
Setting `JVMCI_VERSION` currently doesn't work either because the version match regexp was not update for the 19.x releases.

**Comment by nirvdrum** [comment]
I've opened #1756 to update the regexp so setting `$JVMCI_VERSION` works.

**Comment by eregon** [comment]
I'm on it, I have a PR getting through CI now.

**Comment by eregon** [comment]
I fixed the version lookup mechanism in https://github.com/oracle/truffleruby/commit/0808ffc9e65a98c38a252c87f917e34cff584b28
Thank you for the report.

FWIW the openjdk and oraclejdk `u` differ in this case because they are the respective CPU releases for the 2 different JDKs. We'll just maintain two entries in ci.jsonnet to accommodate that.
