### ISSUE TITLE
Example for Thread#raise in documentation executes very differently

### ISSUE THREAD

**Issue by XrXr** [oracle/truffleruby#1759]
The following snippet from the official documentation doesn't output anything on `truffleruby 19.2.0.1, like ruby 2.6.2, GraalVM CE Native [x86_64-darwin]` 
https://ruby-doc.org/core-2.6.4/Thread.html#method-i-raise

```ruby
Thread.abort_on_exception = true
a = Thread.new { sleep(200) }
a.raise("Gotcha")
```
Adding a puts at the end of the script gives strange a output:

```
$ cat ~/tmp/raise.rb
Thread.abort_on_exception = true
a = Thread.new { sleep(200) }
a.raise("Gotcha")
puts 'hi'
$ bin/ruby -v ~/tmp/raise.rb
truffleruby 19.2.0.1, like ruby 2.6.2, GraalVM CE Native [x86_64-darwin]
#<Thread:0x200@/Users/alanwu/tmp/raise.rb:2 run> terminated with exception:
/Users/alanwu/tmp/raise.rb:2:in `block in <main>': Gotcha (RuntimeError)
hi
/Users/alanwu/tmp/raise.rb:2:in `block in <main>': Gotcha (RuntimeError)
```

Why is the error printed twice?

**Comment by eregon** [comment]
This also happens on MRI by tweaking the script a little (program termination is racy in the code above):
```ruby
Thread.abort_on_exception = true
a = Thread.new { sleep(200) }
a.raise("Gotcha")

puts 'hi'
sleep 1
```
gives (MRI 2.6.3):
```
$ ruby raise.rb |& cat
#<Thread:0x000055c1a7955948@raise.rb:2 run> terminated with exception (report_on_exception is true):
raise.rb:2:in `sleep': Gotcha (RuntimeError)
	from raise.rb:2:in `block in <main>'
raise.rb:2:in `sleep': Gotcha (RuntimeError)
	from raise.rb:2:in `block in <main>'
hi
```
And on TruffleRuby 19.2.0:
```
$ ruby raise.rb |& cat
#<Thread:0x200@raise.rb:2 run> terminated with exception:
raise.rb:2:in `block in <main>': Gotcha (RuntimeError)
raise.rb:2:in `block in <main>': Gotcha (RuntimeError)
hi
```

It is printed once because of Thread.report_on_exception [being true by default on Ruby 2.4+](https://eregon.me/blog/2017/12/28/thread-report-on-exception.html).

And it is printed another time due to `Thread.abort_on_exception` being set to true in this program.
`Thread.abort_on_exception` rethrows the exception on the main thread when a thread dies from an exception.

Is this causing any problem for your use case?

I'll close this issue since we have AFAIK the same behavior as MRI, the only difference being whether the other thread has time to raise the exception in the main thread before the main thread finishes, which depends on thread ordering.
