### ISSUE TITLE
Build failure 19.3.0 with ruby-build and macOS environment

### ISSUE THREAD

**Issue by hsbt** [oracle/truffleruby#1818]
I'm not sure why it's failed. 

```
‚ùØ rbenv install truffleruby-19.3.0
Installing openssl-1.1.1d...
Installed openssl-1.1.1d to /Users/hsbt/.local/share/rbenv/versions/truffleruby-19.3.0

Downloading truffleruby-19.3.0-macos-amd64.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/b2958301dbe0d2ed6dd430ccfb4c06f414a575e2fa6dbd38f6cf7ef63f679550
Installing truffleruby-19.3.0...
/Users/hsbt/.local/share/rbenv/plugins/ruby-build/bin/ruby-build: line 750: ./lib/truffle/post_install_hook.sh: No such file or directory

BUILD FAILED (OS X 10.15.1 using ruby-build 20191111-7-ge61e194)

Inspect or clean up the working tree at /var/folders/jl/zgy9fk353nd6zn0xznlsdzvc6gxzs5/T/ruby-build.20191121114453.3590.oZpusz
Results logged to /var/folders/jl/zgy9fk353nd6zn0xznlsdzvc6gxzs5/T/ruby-build.20191121114453.3590.log

Last 10 log lines:
Last-Modified: Wed, 20 Nov 2019 17:07:16 GMT
ETag: "41daa52f0f308abb77a2b91c1b7e0f3d"
Accept-Ranges: bytes
Server: AmazonS3
X-Cache: Miss from cloudfront
Via: 1.1 66309bee66246372e1bbba43f9725b7f.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: NRT51-C3
X-Amz-Cf-Id: DuZ155VA5MglG2CS7VVlSojaIepf8hc7-JEtNXKboiGR-BqlaHaOPg==

/var/folders/jl/zgy9fk353nd6zn0xznlsdzvc6gxzs5/T/ruby-build.20191121114453.3590.oZpusz/truffleruby-19.3.0 /var/folders/jl/zgy9fk353nd6zn0xznlsdzvc6gxzs5/T/ruby-build.20191121114453.3590.oZpusz ~/Documents/github.com/ruby/ruby
```

Can you give me the point for this failure?

**Comment by eregon** [comment]
Thank you for the report, could you try `rbenv install truffleruby-19.2.0` and see if that works?
It sounds like a `ruby-build` uses a different working directory than before, but that's just a guess.
I'll try to reproduce.

**Comment by eregon** [comment]
I cannot reproduce in Docker on Fedora 28 with `ruby-build truffleruby-19.3.0 $PWD/prefix/`, it works fine there.

And the logic seems fairly straightforward:
```bash
build_package_truffleruby() {
  build_package_copy

  cd "${PREFIX_PATH}"
  ./lib/truffle/post_install_hook.sh
}
```

Could you check what is `$PREFIX_PATH` in your case, and what's under it with `ls $PREFIX_PATH` and `ls $PREFIX_PATH/lib/truffle` ?

**Comment by eregon** [comment]
I also pushed https://github.com/rbenv/ruby-build/commit/f0a393d20a4fe3cbda0d5a10bf7b14b1b524bb0d to `ruby-build` to help debugging, that should print the full path to `post_install_hook.sh`.

**Comment by eregon** [comment]
We found the issue with @pitr-ch.

When installing TruffleRuby with rbenv, on macOS, openssl is downloaded, built and installed first in `$PREFIX_PATH/truffleruby-19.3.0/openssl`.
Then truffleruby is downloaded and extracted by `fetch_tarball`.
The logic in `fetch_tarball` assumes that the `$PREFIX_PATH`, however it is not in this case, since the installation of openssl created `$PREFIX_PATH/truffleruby-19.3.0/openssl`.
Therefore the check to see if the name of the extracted directory matches `$package_name` succeeds even though it should not, and things go wrong from there.

An easy and quick fix is to not install `install_package "openssl"` in truffleruby definitions, because anyway we use openssl from Homebrew, not the one built by `ruby-build`.

The proper fix is to improve the logic in `fetch_tarball` to work even if `$PREFIX_PATH` is not empty, but that's quite a bit more involved.

**Comment by eregon** [comment]
https://github.com/postmodern/ruby-install/pull/315/files is a possible approach for fixing `fetch_tarball`

**Comment by eregon** [comment]
@hsbt https://github.com/rbenv/ruby-build/pull/1383 should fix this, could you confirm?

**Comment by hsbt** [comment]
@eregon Thank you. I can build truffleruby-19.3.0 with https://github.com/rbenv/ruby-build/commit/08af62839635b4cf6b2e21e7a0ddf54000cfa906
