### ISSUE TITLE
`floor': wrong number of arguments

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#1899]
An exeption is taken from [here](https://travis-ci.org/sporkmonger/addressable/jobs/645568855) :
```
/home/travis/build/sporkmonger/addressable/vendor/bundle/truffleruby/19.3.1/gems/simplecov-0.18.1/lib/simplecov.rb:223:in `floor': wrong number of arguments (given 1, expected 0) (ArgumentError)

	from /home/travis/build/sporkmonger/addressable/vendor/bundle/truffleruby/19.3.1/gems/simplecov-0.18.1/lib/simplecov.rb:223:in `process_result'

	from /home/travis/build/sporkmonger/addressable/vendor/bundle/truffleruby/19.3.1/gems/simplecov-0.18.1/lib/simplecov.rb:205:in `run_exit_tasks!'
```

**Comment by eregon** [comment]
I think this is already fixed in 20.1.0: https://github.com/oracle/truffleruby/blob/master/CHANGELOG.md#2010

If using GitHub Actions and https://github.com/ruby/setup-ruby, it would be easy to verify with `truffleruby-head`.

Otherwise I'd suggest to enable Coverage only for MRI as a workaround (`platforms: :mri` in the Gemfile).
It seems the coverage doesn't do anything on JRuby, so there would be no loss there: https://travis-ci.org/sporkmonger/addressable/jobs/645568854

**Comment by eregon** [comment]
https://github.com/dentarg/addressable/runs/434731081?check_suite_focus=true shows it works with `truffleruby-head` and fails as reported with 19.3.1.
So I think we can safely close this, it will be in the 20.1.0 release and feel free to use truffleruby-head to get it immediately.

**Comment by eregon** [comment]
cc @dentarg, using GitHub Actions and `truffleruby-head` would solve the issue for coverage of `addressable`.

**Comment by gogainda** [comment]
Thanks for confirmation
