### ISSUE TITLE
Converted method to proc is given wrong number arguments

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1944]
To reproduce:

```ruby
def register(a, b)
end

{
  1 => 'a',
  2 => 'b'
}.map(&method(:register))

```

Error:

```
pocus.rb:1:in `register': wrong number of arguments (given 1, expected 2) (ArgumentError)
	from pocus.rb:1:in `register'
	from pocus.rb:6:in `map'
	from pocus.rb:6:in `<main>'
```

**Comment by deepj** [comment]
Hm, can you take a look at this soon, please? :) This pattern comes from `command_bus` gem https://github.com/arkency/command_bus

And this blocks me to test the application on what I'm currently working full-time since this fails already while booting the application. The previous was https://github.com/oracle/truffleruby/issues/1934 and this issue is followed after that one. I can't comment it out because the whole application is based on CQRS :)

**Comment by eregon** [comment]
This is caused by TruffleRuby defining Hash#map and not checking the block arity like it's done in `each`.
Two solutions:
* Check the arity of the block in HashNodes.MapNode
* Just use Enumerable#map which already has the correct behavior since @bjfish's fix.

I'll do the first one as it seems a bit safer performance-wise.

**Comment by deepj** [comment]
@eregon Thanks! If you can release nightly build with this fix I can keep further and try it again
