### ISSUE TITLE
Support for other JVMs?

### ISSUE THREAD

**Issue by MadHau5** [oracle/truffleruby#1968]
Does TruffleRuby support other JVMs like Hotspot or OpenJ9?
I am only asking this as I prefer to use OpenJ9 and want to confirm whether it runs on other JVMs or just on GraalVM. Thanks in advance.

**Comment by eregon** [comment]
The short answer is TruffleRuby requires GraalVM.
TruffleRuby is also distributed as a [standalone native distribution](https://github.com/oracle/truffleruby/blob/master/doc/user/standalone-distribution.md) where it's compiled ahead-of-time to a native binary by GraalVM Native Image.

Specifically, to just-in-time compile Ruby code, Truffle needs JVMCI and that doesn't seem implemented on other JVMs than Hotspot currently (see https://github.com/eclipse/openj9/issues/59 for OpenJ9).

TruffleRuby itself is pure Java, but running it without JIT compilation would be of little interest because the performance would then be very slow.
