### ISSUE TITLE
Missing x.pow(e, m) method

### ISSUE THREAD

**Issue by jzakiya** [oracle/truffleruby#2000]
Running working Ruby code in 2.7.1, et al, with Truffleruby 20.0.0 gives missing ``pow`` error.
```
def xyz
...
y = b.pow(d, self) 
...
end
```
Gives this error.

```
 number = 2147483647 is prime? millerrabin1.rb:26: warning: in a**b, b may be too big
millerrabin1.rb:28:in `block in miller_rabin_test': undefined method `pow' for NaN:Float (NoMethodError)
```
Doing this works.
```
require "openssl"

def xyz
...
y = b.to_bn.mod_exp(d, self)
...
end
```

**Comment by eregon** [comment]
We have Integer#pow (but it's not fast yet, #1999), and Float#pow doesn't exist (neither on MRI 2.6.5 & 2.7.1).

The issue is likely due to the warning above: `warning: in a**b, b may be too big`.
Which means `**` will return a Float and not an Integer.

Could you share a complete reproduction script that works on MRI and fails on TruffleRuby?

**Comment by jzakiya** [comment]
Here is the code that the error comes from.
The method ``pow()`` is the culprit, as noted in #1999.


https://rosettacode.org/wiki/Miller%E2%80%93Rabin_primality_test#Deterministic_for_integers_.3C_3.2C317.2C044.2C064.2C679.2C887.2C385.2C961.2C981

**Comment by bjfish** [comment]
This example appears to run on the current master but the issue description mentions `Truffleruby 20.0.0` : https://github.com/oracle/truffleruby/commit/6e19c7a008c0df9e04e070db635b8b98c3f0fdf2
>https://rosettacode.org/wiki/Miller%E2%80%93Rabin_primality_test#Deterministic_for_integers_.3C_3.2C317.2C044.2C064.2C679.2C887.2C385.2C961.2C981
