### ISSUE TITLE
[interop] Ruby strings show odd behavior from JavaScript

### ISSUE THREAD

**Issue by fniephaus** [oracle/truffleruby#2037]
The interface of Ruby strings is not automatically changed to that of JavaScript when passed to JS. The reason for this is probably that Ruby strings are mutable. Python strings for example aren't, and behave as expected. Nonetheless, I was very surprised to see `DynamicObjectBasic` shining through:

#### Behavior on GraalVM CE 20.1.0
```
$ polyglot --jvm --shell
GraalVM MultiLanguage Shell 20.1.0
Copyright (c) 2013-2019, Oracle and/or its affiliates
  JavaScript version 20.1.0
  Python version 3.8.2
  Ruby version 2.6.5
  Squeak/Smalltalk version 20.1.0
js> let string1 = Polyglot.eval('ruby', '"Test"')
js> string1.length
com.oracle.truffle.object.DynamicObjectBasic@5f9d29c4
js> string1.indexOf('s')
TypeError: invokeMember (indexOf) on com.oracle.truffle.object.DynamicObjectBasic@5f7cc6fd failed due to: Unknown identifier: indexOf
js> string1.index('s')
2
js> let string2 = Polyglot.eval('python', '"Test"')
js> typeof(string2)
string
js> string2.length
4
js> string2.__len__()
TypeError: (intermediate value).__len__ is not a function
```

#### Behavior on GraalVM CE 19.3.0
```
$ polyglot --shell --jvm
GraalVM MultiLanguage Shell 19.3.0
Copyright (c) 2013-2019, Oracle and/or its affiliates
  JavaScript version 19.3.0
  Python version 3.7.4
  Ruby version 2.6.2
js> let string1 = Polyglot.eval('ruby', '"Test"')
js> typeof(string1)
string
js> string1.length
null
js> string1.indexOf('s')
undefined method `indexOf' for "Test":String
Did you mean?  index (NoMethodError)
js> string1.index('s')
2
```

**Comment by eregon** [comment]
I would guess that's because both JS and Python use java.lang.String (but maybe not always for Python?), while Ruby must use a byte[]-based representation of Strings for semantics.
There is ongoing work by @djoooooe on TruffleString which might help solve this.

Anyway, this looks like an issue in JavaScript to me, objects which are InteropLibrary#isString() should be treated just like that language's Strings.

TruffleRuby [basically never converts Ruby Strings to Java Strings](https://github.com/oracle/truffleruby/blob/master/doc/contributor/interop.md#string-conversion) (except member names) when they go to a foreign language, since that would lose the mutability and identity, and break C extensions.

**Comment by eregon** [comment]
@fniephaus Would you mind re-filing the issue on https://github.com/graalvm/graaljs? I think that would make it easier to track. Unfortunately I cannot just transfer the issue as it's different GitHub organizations.

**Comment by fniephaus** [comment]
Done!
