### ISSUE TITLE
Gem installation failure: no member named flags in struct RBasic

### ISSUE THREAD

**Issue by djberg96** [oracle/truffleruby#2067]
Hi,

I hit this when attempting to install `memory_buffer` on my Mac (~~in reality a dependency of sassc-rails~~),  and figured I should mention it:

truffleruby 20.1.0, like ruby 2.6.5, GraalVM CE Native [x86_64-darwin]

```
>gem install memory_buffer
Building native extensions. This could take a while...
ERROR:  Error installing memory_buffer:
	ERROR: Failed to build gem native extension.

current directory: /Users/dberger/.rbenv/versions/truffleruby-20.1.0/lib/gems/gems/memory_buffer-0.1.0/ext/memory_buffer
/Users/dberger/.rbenv/versions/truffleruby-20.1.0/bin/truffleruby -I /Users/dberger/.rbenv/versions/truffleruby-20.1.0/lib/mri -r ./siteconf20200806-89969-1rxo5k0.rb extconf.rb
creating Makefile

current directory: /Users/dberger/.rbenv/versions/truffleruby-20.1.0/lib/gems/gems/memory_buffer-0.1.0/ext/memory_buffer
make "DESTDIR=" clean

current directory: /Users/dberger/.rbenv/versions/truffleruby-20.1.0/lib/gems/gems/memory_buffer-0.1.0/ext/memory_buffer
make "DESTDIR="
compiling memory_buffer.c
memory_buffer.c:39:15: error: no member named 'flags' in 'struct RBasic'
        RBASIC(asb)->flags |= RSTRING_NOEMBED;
        ~~~~~~~~~~~  ^
1 error generated.
make: *** [memory_buffer.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/dberger/.rbenv/versions/truffleruby-20.1.0/lib/gems/gems/memory_buffer-0.1.0 for inspection.
Results logged to /Users/dberger/.rbenv/versions/truffleruby-20.1.0/lib/gems/extensions/x86_64-darwin/20.1.0/memory_buffer-0.1.0/gem_make.out
```

**Comment by gogainda** [comment]
works for me with latest truffle ruby:
```
gem install memory_buffer                                                   [6/08/20 | 9:50:39]
Fetching memory_buffer-0.1.0.gem
Building native extensions. This could take a while...
Successfully installed memory_buffer-0.1.0
1 gem installed
novoi@L35975MEU-2 tmp % ruby -v                                                                     [6/08/20 | 9:52:00]
truffleruby 20.3.0-dev-9220194b, like ruby 2.6.6, GraalVM CE Native [x86_64-darwin]
```

**Comment by gogainda** [comment]
thought I see that tests are failing:
```
MemoryBuffer
  has a version number
  .create_aligned (FAILED - 1)
  .create_quad
  .create_long
  .create_short
  .create
    with 1 bytes
    with 151 bytes
    with 152 bytes
    with 1024 bytes
    with 1048576 bytes
    with 545259518 bytes
    with 545259519 bytes
    with 1073741824 bytes

Failures:

  1) MemoryBuffer .create_aligned
     Failure/Error: buf = MemoryBuffer.create_aligned(alignment, length)
     
     RuntimeError:
       Can not write array element 3. (LLVMPolyglotException)
       Translated to internal error
     # ./ext/memory_buffer/memory_buffer.c:41:in `mb_create_aligned'
     # /Users/novoi/.rubies/truffleruby-dev/lib/truffle/truffle/cext_ruby.rb:39:in `create_aligned'
     # ./spec/memory_buffer_spec.rb:13:in `block (2 levels) in <top (required)>'

Finished in 32.27 seconds (files took 1.18 seconds to load)
13 examples, 1 failure

Failed examples:

rspec ./spec/memory_buffer_spec.rb:10 # MemoryBuffer .create_aligned

/Users/novoi/.rubies/truffleruby-dev/bin/truffleruby -I/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/lib:/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-support-3.9.3/lib /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.9.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

**Comment by bjfish** [comment]
For reference, the code that is failing:

https://github.com/ManageIQ/memory_buffer/blob/4b9601981f6dca82ca64081c4a28171ac91ff5af/ext/memory_buffer/memory_buffer.c#L41-L42

**Comment by eregon** [comment]
```c
	RSTRING(asb)->as.heap.ptr = abuf;
	RSTRING(asb)->as.heap.aux.capa = len;
```

That code pokes at CRuby internals and I wouldn't be surprised if it breaks in the next CRuby versions.
I am thinking it's not  reasonable to implement these RString internals in TruffleRuby.
I'm unclear what this gem is for.
If it's really needed then probably TruffleRuby would need to expose an API to create a native String from an existing allocation, and that allocation must be fine to be deallocated with `free()`. Still, it's very fragile.

`sassc-rails 2.4.0` does not depend on `memory_buffer` as far as I can see:
https://gist.github.com/eregon/bcdf13f10f394fb9bc1741dc50adb67b

@djberg96 Could you look in your `Gemfile.lock` what depends on `memory_buffer`?

**Comment by djberg96** [comment]
@eregon You're right, i misread my output (it happened just after the sassc-rails install, that's why I thought that). It's a dependency of one of our own libraries at https://github.com/ManageIQ/manageiq-smartstate/blob/master/manageiq-smartstate.gemspec#L28

**Comment by Fryguy** [comment]
> I'm unclear what this gem is for.

One of the purposes of the gem (at least the part in the C extension), is to create a Ruby string that is memaligned.  At the time we wrote this (and probably still today?), there was no way to do it directly with Ruby, so the C code creates a memaligned buffer, then creates a Ruby String, then just swaps out the internal Ruby String with the buffer.  Is it a hack?  Yup!  If there's another way to do this now, we can definitely change it.  @djberg96 It might even be worth investigating if we need this function anymore, since it's only called from one place.

> That code pokes at CRuby internals and I wouldn't be surprised if it breaks in the next CRuby versions.

I laughed out loud only because the code was written in 2013 and hasn't changed for the last 7 years.  Ruby is amazingly stable.  That being said, if a moving garbage collector were implemented that moved the string allocations, then yeah, this would break.

**Comment by eregon** [comment]
The only usage of `create_aligned` in `manageiq-smartstate` seems to be:
https://github.com/ManageIQ/manageiq-smartstate/blob/818219ec146d16c6e4323ca166fd669c11034945/lib/disk/modules/RawBlockIO.rb#L102

Does it need to be aligned there, or is it optional but improves performance?
If it's optional, I'd suggest some kind of fallback in `memory_buffer` or `manageiq-smartstate`.

Technically it might be possible to support such a pattern in TruffleRuby but:
* it would be a large effort for such a corner case.
* it would be unreliable in general (see below).

> That being said, if a moving garbage collector were implemented that moved the string allocations, then yeah, this would break.

Like `GC.compact`? Luckily for now it will not move externally-allocated memory (e.g., malloc). But I could imagine the RString flags change.

It could also segfault if the `free()` used doesn't match the allocation used, maybe when using jemalloc, etc.
I think that's the main reason CRuby does not allow to allocate your own String, because then it cannot reliably free it.
See https://bugs.ruby-lang.org/issues/15923

On TruffleRuby native strings will be allocated by `Unsafe.allocateMemory()` and freed by `Unsafe.freeMemory()`, which might or not use malloc()/free().

**Comment by eregon** [comment]
The original issue is `no member named flags in struct RBasic` and that much is implemented.
Feel free to open a separate issue for this `RSTRING(asb)->as.heap.` usage.
