### ISSUE TITLE
Potential performance degradation of method_missing

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2080]
Hi,
I created a fork of fast-ruby project to track the performance changes between different version of truffleruby. After the last run I noticed one deviation:
- results for truffleruby 20.3.0-dev-c60f3a13
```
method_missing: 2134367774.5 i/s
                   send: 2126284730.6 i/s - same-ish: difference falls within error
                      call: 2106937723.2 i/s - same-ish: difference falls within error
```
- results for truffleruby 20.3.0-dev-cc7f184c (later version)
```
                    call: 3208393073.8 i/s
                  send: 2300256356.0 i/s - 1.39x  (± 0.00) slower
method_missing: 1089096506.2 i/s - 2.95x  (± 0.00) slower
```
both runs were executed on the same laptop.

I understand that simply comparing absolute numbers  it's not correct, but relative numbers should stay the same or improve ( e.g. the "slower" index). 

Not saying that this is definitely an issue, but probably needs your attention 

The full diff is [here](https://github.com/gogainda/fast-truffleruby/commit/94958a44cdc5f2b5aeb0bc946fc235166fa35088#diff-04c6e90faac2675aa89e2176d2eec7d8) 

Side note: overall numbers are much better comparing to the last run

**Comment by eregon** [comment]
I can reproduce with a single run:
```
ruby -v
truffleruby 20.3.0-dev-cc7f184c, like ruby 2.6.6, GraalVM CE Native [x86_64-linux]

ruby call-vs-send-vs-method_missing.rb
Warming up --------------------------------------
                call   429.668M i/100ms
                send   209.205M i/100ms
      method_missing    96.875M i/100ms
Calculating -------------------------------------
                call      4.293B (± 1.6%) i/s -     21.483B in   5.005095s
                send      1.905B (±28.0%) i/s -      8.159B in   5.194053s
      method_missing      1.239B (±58.5%) i/s -      4.456B in   5.058901s

Comparison:
                call: 4293383974.2 i/s
                send: 1904518089.1 i/s - 2.25x  (± 0.00) slower
      method_missing: 1239225771.7 i/s - 3.46x  (± 0.00) slower
```

When using `x.iterations = 3` to make sure ordering doesn't change anything and it has enough time to stabilize, the numbers seem very close:
```
ruby call-vs-send-vs-method_missing.rb
Warming up --------------------------------------
                call   425.029M i/100ms
                send   210.590M i/100ms
      method_missing   211.758M i/100ms
                call   211.320M i/100ms
                send    63.883M i/100ms
      method_missing   211.757M i/100ms
                call    61.568M i/100ms
                send   211.370M i/100ms
      method_missing   211.655M i/100ms
Calculating -------------------------------------
                call      1.416B (±50.4%) i/s -      5.110B in   5.018550s
                send      2.072B (±13.5%) i/s -      9.934B in   5.042269s
      method_missing    651.396M (±21.4%) i/s -      3.386B in   5.336569s
                call      1.216B (±60.9%) i/s -      4.371B in   5.088346s
                send      1.929B (±26.3%) i/s -      8.243B in   5.109303s
      method_missing      2.128B (± 0.6%) i/s -     10.794B in   5.071942s
                call      1.968B (±23.5%) i/s -      8.496B in   5.007090s
                send      2.055B (±13.7%) i/s -      9.934B in   5.072772s
      method_missing      1.946B (±25.0%) i/s -      8.466B in   5.093436s

Comparison:
                send: 2055275121.2 i/s
                call: 1967683850.3 i/s - same-ish: difference falls within error
      method_missing: 1946204219.8 i/s - same-ish: difference falls within error
```

Note that it is in billions of iterations per second, in other words the benchmark is optimized and comparing those is going to be not representative of real code. But it's still nice that it does optimize away all 3 forms.

Still a bit surprising that the numbers are not stable on the first run though.

**Comment by eregon** [comment]
The issue seems to be since the number of iterations is so high, at some point a `long` instead of an `int` is passed to benchmark-ips's `call_times(n)` and that causes extra branches. Other than that the compiler graphs seem identical.

**Comment by eregon** [comment]
There is definitely something a bit strange here where we get `long` but actually they would fit an `int`:
https://gist.github.com/eregon/8a00db1e9232cc82537037910413f93a

**Comment by eregon** [comment]
So it's this code:
https://github.com/evanphx/benchmark-ips/blob/5a2dc713fede28e0c08d2c9d43efad967cba6019/lib/benchmark/ips/job.rb#L266

During warmup for the first job (call), we actually compute we can run 1073741824 iterations in the remaining half warmup time.
```
[268435456, "Integer"]
[:after_double, 536870912, "Integer"]
[536870912, "Integer"]
[:after_double, 1073741824, "Integer"]
[1073741824, "Integer"]
[:after_double, 2147483648, "Long"]
```
And then `cycles` is doubled after even though it's not used, unfortunate.

Warmup for next job will then always use `long` because `cycles` is now stored as a `long` in the frame (`WriteFrameSlotNode` does this to avoid extra polymorphism & boxing).
```
[:after_double, 2, "Long"]
[2, "Long"]
[:after_double, 4, "Long"]
[4, "Long"]
[:after_double, 8, "Long"]
[8, "Long"]
[:after_double, 16, "Long"]
[16, "Long"]
```

If I change the code to `break` before doubling the cycles with `break unless Timing.now + warmup_time_us * 2 < target`, then I see the expected results:
```
Comparison:
                call: 4243906485.6 i/s
                send: 4235867337.7 i/s - same-ish: difference falls within error
      method_missing: 4209656910.8 i/s - same-ish: difference falls within error
```

**Comment by gogainda** [comment]
So to have more reliable results I should add ```x.iterations = 3``` to every benchmark?

**Comment by chrisseaton** [comment]
@gogainda I think this problem with `benchmark-ips` was fixed but possibly not. It's documented here:

https://github.com/Shopify/truffleruby/blob/master/doc/user/reporting-performance-problems.md#how-to-write-a-performance-benchmark

**Comment by eregon** [comment]
I'll make a PR to benchmark-ips to fix this, almost done.

**Comment by eregon** [comment]
PR for benchmark-ips: https://github.com/evanphx/benchmark-ips/pull/106

`x.iterations = 3` (or `x.iterations = 2`) is a useful help to avoid ordering bias between the different blocks being benchmarked, at the cost of taking longer to benchmark.
Such bias can come from various sources including the benchmark harness (like here), interactions between the different benchmark blocks (for instance if they call a common method with different arguments), etc.
I'd consider `x.iterations =` a good way to debug a benchmark and to make sure the results are stable, but I would think in most cases it's not needed.

To some degree the warmup + measure runs of benchmark-ips already avoid some ordering bias since benchmark-ips runs blocks like this: block1 warmup, block2 warmup, block1 measure, block2 measure. In this case it was really unlucky that the overflow happened just after `block1 warmup` finished, and so the compiled version of block1 never had to consider `long` cycles, but the others blocks had to.

In this case the real issue was the overflow, and the reported results are much closer to the truth with that fix.
`x.iterations =` as above caused all benchmark blocks to see the overflow so there would be no bias, but they would also be 2x slower than without the overflow.

**Comment by eregon** [comment]
@gogainda And I forgot to say, thanks for https://github.com/gogainda/fast-truffleruby! I think it could make a nice blog post debunking "X is faster than Y" for some of the cases when really it's only "X is faster than Y in the current version of CRuby, but actually on a highly optimizing implementation it makes no significant difference".

**Comment by gogainda** [comment]
@eregon thank for the thorough investigation, I am planning to continue running the benchmarks from fast-truffleruby and probably even will try to automate it.

I expected that some of the performance optimizations are not applied for the truffleruby implementation and in some cases could be even dangerous, so I created the repo to prove it. I am glad that you found it useful

**Comment by eregon** [comment]
benchmark-ips 2.8.3 [was released](https://github.com/evanphx/benchmark-ips/pull/106#issuecomment-682592879) with this fix and the results look as expected:
```
$ truffleruby call-vs-send-vs-method_missing.rb
Warming up --------------------------------------
                call   425.684M i/100ms
                send   424.601M i/100ms
      method_missing   424.842M i/100ms
Calculating -------------------------------------
                call      4.240B (± 0.4%) i/s -     21.284B in   5.020099s
                send      4.241B (± 0.7%) i/s -     21.230B in   5.005800s
      method_missing      4.237B (± 0.7%) i/s -     21.242B in   5.014280s

Comparison:
                send: 4241293198.3 i/s
                call: 4239869985.4 i/s - same-ish: difference falls within error
      method_missing: 4236536442.8 i/s - same-ish: difference falls within error
```
