### ISSUE TITLE
Tempfile#path returns a copy of the original string on CRuby, but not on truffleruby

### ISSUE THREAD

**Issue by deivid-rodriguez** [oracle/truffleruby#2115]
The following script runs fine on CRuby:

```ruby
# frozen_string_literal: true

require "tempfile"

f = Tempfile.open("foo") do |tmp|
  foo = tmp.path
  foo[0] = "💀"
  tmp
end

File.delete(f.path)
```

But on truffleruby, it crashes with the following error:

```
$ ruby foo.rb 
<internal:core> core/errno.rb:48:in `handle': No such file or directory (Errno::ENOENT)
	from <internal:core> core/file.rb:1153:in `block in unlink'
	from <internal:core> core/file.rb:1151:in `each'
	from <internal:core> core/file.rb:1151:in `unlink'
	from foo.rb:11:in `<main>'
```

Forcing a copy of the string so that the Tempfile itself is not mutated workarounds the issue:

```diff
diff --git a/foo.rb b/foo.rb
index d255a34..24c8e18 100644
--- a/foo.rb
+++ b/foo.rb
@@ -3,7 +3,7 @@
 require "tempfile"
 
 f = Tempfile.open("foo") do |tmp|
-  foo = tmp.path
+  foo = tmp.path.dup
   foo[0] = "💀"
   tmp
 end
```

**Comment by eregon** [comment]
Thanks for the report.

Since TruffleRuby just uses `tempfile.rb` from MRI, and Tempfile#path is https://github.com/oracle/truffleruby/blob/f65ce6fe531764c2c43e626f677cded9ac752b30/lib/mri/tempfile.rb#L220-L222
It seems this is an issue of File#path:
https://github.com/oracle/truffleruby/blob/f65ce6fe531764c2c43e626f677cded9ac752b30/src/main/ruby/truffleruby/core/file.rb#L111
Should be a trivial fix.
