### ISSUE TITLE
String interpolation requires additional step in debugger

### ISSUE THREAD

**Issue by fniephaus** [oracle/truffleruby#2125]
When I debug the following, I have to step over the line starting with `data = ...` twice:
```ruby
require "open-uri"
require "json"

method = "get"
data = JSON.parse(open("http://httpbin.org/#{method}", &:read))
puts data
```

It's not the case if I don't use string interpolation. @eregon is already working on a fix...

**Comment by eregon** [comment]
The issue seems that the  `LocalVarParseNode` for `method` is marked as `newline` in the JRuby AST, as well as the `data = ...` assignment, so then we have 2 nodes on the same line being recognized as statement.
TruffleRuby uses this `newline` marking from the JRuby AST to mark statements.

This also seems an issue on JRuby master jruby/jruby@2d12159ade4dc1fc062ec2480e280d9723068eee.
To mark newline nodes with `NL`:
```diff
diff --git a/core/src/main/java/org/jruby/ast/Node.java b/core/src/main/java/org/jruby/ast/Node.java
index c4844917be..efd6bd9f8d 100644
--- a/core/src/main/java/org/jruby/ast/Node.java
+++ b/core/src/main/java/org/jruby/ast/Node.java
@@ -160,6 +160,10 @@ public abstract class Node implements ISourcePositionHolder, ISourcePosition {
 
         builder.append(" line: ").append(getPosition().getLine());
 
+        if (newline) {
+          builder.append(" NL");
+        }
+
         String extraInfo = toStringExtraInfo();
         if (extraInfo != null) builder.append(", ").append(extraInfo);
 
```

```ruby
city = "New York"

s = "a #{city} b"

p s
```

```
PATH=$PWD/bin:$PATH bin/ast test.rb
AST:
RootNode line: 0
  BlockNode line: 0
    LocalAsgnNode:city line: 0 NL
      StrNode line: 0
    LocalAsgnNode:s line: 2 NL
      DStrNode line: 2
        StrNode line: 2
        EvStrNode line: 2
          LocalVarNode:city line: 2 NL
        StrNode line: 2
    FCallNode:p line: 4 NL
      ArrayNode line: 4
        LocalVarNode:s line: 4
```

We see `NL` for line 2 on both `LocalAsgnNode:s` (correct) and `LocalVarNode:city` (seems incorrect).

**Comment by eregon** [comment]
While trying to debug this, I noticed JRuby marks every `;` as `newline`:
```ruby
def foo
  "test"
end

s = (p :before; r="a #{foo} b"; p :after; r)

p s
```

```
PATH=$PWD/bin:$PATH bin/ast test2.rb
AST:
RootNode line: 0
  BlockNode line: 0
    DefnNode:foo line: 0 NL
      ArgsNode line: 1
        ListNode line: 1
        ListNode line: 1
        ListNode line: 1
        ListNode line: 1
      StrNode line: 1 NL
    LocalAsgnNode:s line: 4 NL
      BlockNode line: 4
        FCallNode:p line: 4 NL
          ArrayNode line: 4
            SymbolNode:before line: 4
, null
        LocalAsgnNode:r line: 4 NL
          DStrNode line: 4
            StrNode line: 4
            EvStrNode line: 4
              VCallNode:foo line: 4 NL
            StrNode line: 4
        FCallNode:p line: 4 NL
          ArrayNode line: 4
            SymbolNode:after line: 4
, null
        LocalVarNode:r line: 4 NL
    FCallNode:p line: 6 NL
      ArrayNode line: 6
        LocalVarNode:s line: 6
, null
```
See all the `4 NL`.
So maybe the `#{}` of String interpolation is considered an "end of statement", similar to `;`?

Should we stop multiple times if there are `;` on the same line in the debugger with `next`?

**Comment by eregon** [comment]
JRuby only reports the line once for `Coverage` and `TracePoint` though, so I guess there is some logic to only count lines once.

**Comment by enebo** [comment]
@eregon There is history here and JRuby acts the same way as MRI (or at least unless something changed recently).  newline in AST used to be a full node and not an attribute circa (1994-2012?).  It represents a statement demarcation...and yes it was called newline.  JRuby realized this could just be a field on the node and at some point MRI also came to the same conclusion and neither implementation changed the name from newline.

I think both MRI and JRuby end up tracking and only emitting the first NL we see (we are emitting instrs as part of parsing so this is pretty easy).

**Comment by eregon** [comment]
@enebo Thank you for the explanation :)
Do you know where the code to detect the actual new lines is in JRuby? Is it like a `boolean[]`, or something else?

It seems the least-deep `NL` should be used as a "line marker". That means we probably need an extra pass for that, or check the flag before recursing into children, as leaf nodes are explored first with the visitor.

I wonder how hard it would be in the lexer to add a "line" flag, maybe that's a good way too.

**Comment by enebo** [comment]
@eregon for eventing we generate lists of instrs so we record the last line emitted and if it is the one we are currently processing we know we already have emitted a line/event for it and skip the duplicates.  The natural traversal ends up being proper order for this.

You could add another flag for this.  I do also wonder how much we use newline for statement reasons at this point as well.  That is may be a deep hole to fall into but it is possible newline as a field is much less important than in the past.  There used to be one case where a newline node would wrap a child node and because the child was indirectly accessible through a newline node it do something else in the AST interp :)  This is now a field on the node and MRI/JRuby both generate instrs from the tree so it is also possible it is an artifact of an older design.  Ruby's parsing/lexing is very "organic" so some times this is difficult to figure out.

**Comment by eregon** [comment]
This has been fixed with Prism.
