### ISSUE TITLE
Kernel#binding isn't using the right binding from inside a C extension

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#2171]
```ruby
require 'rbconfig'

File.write("bad-ext.c", <<-EOM)
#include <stdlib.h>
#include "ruby.h"

VALUE
change_local(VALUE self)
{
  VALUE binding = rb_funcall(self, rb_intern("binding"), 0);
  rb_funcall(binding, rb_intern("local_variable_set"), 2, ID2SYM(rb_intern("foo")), ID2SYM(rb_intern("bar")));
  return Qnil;
}

void
Init_bad(void)
{
  rb_define_global_function("change_local", change_local, 0);
}
EOM

Process.spawn(Gem.ruby, '-rmkmf', '-e', 'create_makefile("bad")')
Process.wait

`make`

require_relative 'bad'

foo = :foo
change_local
p foo
```

```
% ruby -v test.rb
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
creating Makefile
:bar
% dev jt ruby -v test.rb       
truffleruby (Shopify) 21.0.0-dev-6eab6c44, like ruby 2.7.2, Interpreted JVM [x86_64-darwin]
creating Makefile
```

We've obviously got intermediate frames between the Ruby code and our C extension code, due to C extensions being implemented in Ruby. How do we reach back and find the right frame?

First step would be a spec.

Thanks to @XrXr for finding.

**Comment by eregon** [comment]
IMHO anything that accesses the frame or binding within a core method or a C extension is  not well defined.
Is there real code depending on this?
If not, I'm not sure it's worth the effort to try to emulate this unclear behavior.

I am not sure we can reasonably fix it for `rb_funcall(self, rb_intern("binding"), 0);`.
The caller of Kernel#binding in that case is whatever is around `rb_funcall()`, which is the C extension function/method, so it should return a Binding of that C extension method, and that's what it does on TruffleRuby.
So arguably TruffleRuby is correct here, and MRI is just leaking an implementation detail that C extension methods are not real methods for that specific case.
There are other cases where the C extension method is considered a real method and not skipped, such as `rb_block_proc()` which needs to consider the frame of the C extension method: https://github.com/oracle/truffleruby/blob/aa11d31adb031302a3b9e04d95c0376858c86b72/lib/truffle/truffle/cext_ruby.rb#L12-L16

If there is some C function to access the caller binding, then it might be feasible to handle that case to capture the first non-cext frame. Then at least it would be clear it's the caller of the C extension method, and not the caller of rb_funcall().

**Comment by chrisseaton** [comment]
> So arguably TruffleRuby is correct here, and MRI is just leaking an implementation detail that C extension methods are not real methods for that specific case.

That's what I thought as well. Can you set local variables in a C extension method, for example?

**Comment by eregon** [comment]
In TruffleRuby, yes, because there is an [actual Ruby method](https://github.com/oracle/truffleruby/blob/aa11d31adb031302a3b9e04d95c0376858c86b72/lib/truffle/truffle/cext_ruby.rb#L22-L42) calling the C function. In MRI most likely not.
If it seems worth to fix this, we'd need to pass some flag to https://github.com/oracle/truffleruby/blob/df6d1b8da8ef4dcd99a5ca831789a4bb80c13e17/src/main/java/org/truffleruby/language/arguments/ReadCallerDataNode.java#L52 so to skip such Ruby methods for C functions.

Not sure it's a good idea that C extensions get a Binding from the Ruby caller though :p
So I'd like to know if there is real code needing this and why.

**Comment by chrisseaton** [comment]
> So I'd like to know if there is real code needing this and why.

Just a demo.

**Comment by daveola** [comment]
Here's some real code - anyone who wants to implement their own version of eval.  Kernel::eval has some magical access to it's binding thanks to almost exactly this same pathway.

So if anyone wants to build their own eval, whether it's perhaps something that first checks the code before doing eval, or maybe does a debug logging of the eval before doing the eval, taking this out *without also providing a way for the C extension to access the previous frames binding* - you are breaking this code.

There's a related issue (because the binding is not actually completely generated and does not include 'self' in this Bug:

https://bugs.ruby-lang.org/issues/18487

Please do not remove the only access that C extensions have to the calling frame without providing some sort of support to this information.  TruffleRuby took away this path through 'binding' but provides other support.

**Comment by eregon** [comment]
We'll follow CRuby here, and since https://bugs.ruby-lang.org/issues/18487 CRuby's Kernel#binding raises a RuntimeError if it is called from a non-Ruby frame (the sensible thing to do). We just need to check TruffleRuby does the same (currently it might return an empty Binding) and add a spec for it, and then close this issue.

> Here's some real code

Where is the real code? Anyway, you can continue discussing on https://bugs.ruby-lang.org/issues/18780 (or a new CRuby issue with a clear explanation of what you'd like), here is not the place.

**Comment by eregon** [comment]
There is already a spec in https://github.com/ruby/ruby/pull/5567/files#diff-b5aa67ac2808791677a9de1757bca05d77baa6bcdf77fa75df6a177cc45b6a70, great.
