### ISSUE TITLE
Expand what's run in GitHub Actions

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#2180]
We'd like the majority of tests to be run in GitHub Actions. This should probably cover all specs, and possibly compiler tests. Maybe not the larger integration tests that depend on external gems and things.

**Comment by eregon** [comment]
That sounds good in general.

I actually tried to run all specs on GitHub Actions, but it seems there is some issue with signals:
https://github.com/eregon/truffleruby/runs/1458899992?check_suite_focus=true
I didn't have time to investigate yet, so it would be helpful if someone else can look into that.

**Comment by chrisseaton** [comment]
Yes we'll invest time in this at Shopify.

**Comment by eregon** [comment]
In that log, it looks like something "catches" these signals and prints them, maybe actions/runner or some shell is doing that somehow?
See
```
Killed
Profiling timer expired
User defined signal 1
Killed
Killed
Killed
Killed
Killed
Terminated
Killed
Terminated
```
at the beginning of the log.

**Comment by nirvdrum** [comment]
It wouldn't be ideal, but I think you could run the tests/specs within a Docker container and avoid issues with the host environment intercepting signals.

**Comment by eregon** [comment]
Looking a bit more into this, the `ruby_exe` calls of `spec/ruby/core/exception/signal_exception_spec.rb` end up using a shell:
```
should_use_shell?("/home/eregon/code/truffleruby-ws/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/bin/truffleruby --vm.ea --vm.esa --experimental-options --core-load-path=/home/eregon/code/truffleruby-ws/truffleruby/src/main/ruby/truffleruby --vm.Xmx2G --polyglot /home/eregon/code/truffleruby-ws/truffleruby/rubyspec_temp/91304/1-rubyexe.rb"): true
```
because there is an `=` in there.

In that case we use `/bin/sh`, and that might differ from MRI, and the `/bin/sh` shell might be special on GitHub Actions.

**Comment by eregon** [comment]
Actually, MRI seems to not use a shell just because there is a `=`, so it doesn't use a shell for
`ruby -e 'system "a=1 sleep 500"'` (and it then needs to parse that env var being set).

With `ruby -e 'system "a=1; sleep 500"'` it does use a shell, which seems to be `/bin/sh` and resolves to `/usr/bin/bash` my system.
```
$ ruby -e 'p File.binread ARGV[0]' /proc/92211/cmdline
"sh\x00-c\x00a=1; sleep 500\x00"
```

**Comment by eregon** [comment]
Using `-- --no-core-load-path` works around the issue, as it removes the `=`.
So we could use that, or improve the detection for `=`, or rewrite these specs to make sure they never use a shell.

**Comment by eregon** [comment]
I fixed the detection for `=` in subprocess commands in https://github.com/oracle/truffleruby/commit/bcae566cfafab9a4adc9f3142f28565fb72e46d5

**Comment by eregon** [comment]
Making progress here with a pipeline build:
![Screenshot from 2021-01-04 23-37-18](https://user-images.githubusercontent.com/168854/103586669-da302e00-4ee5-11eb-98f5-a5c9c7765cdd.png)

* lint is run separately as most of it doesn't need to build, only SpotBugs needs a build, and that's done last (we discussed this a bit at some point with @tomstuart)
* running all specs in the same job is long, I'm going to split it

Still need `jt test compiler` and a native build. Potentially run command line specs on native instead of JVM for efficiency.

**Comment by chrisseaton** [comment]
Looks great thanks!

As discussed already, I think our baseline requirements from my team are:

* all specs, ideally split up not only for time, but also because seeing failures in the different areas easily is good
* a native build, to catch AOT compilation of the interpreter issues

**Comment by eregon** [comment]
Should be good now, I'll merge that branch:
https://github.com/eregon/truffleruby/actions/runs/463528887
![Screenshot from 2021-01-05 16-02-57](https://user-images.githubusercontent.com/168854/103661955-9c77e780-4f6f-11eb-9329-9891dbbaf6f1.png)

**Comment by chrisseaton** [comment]
Is there a reason you associated testing the compiler with native specifically?

**Comment by eregon** [comment]
Just convenience, since `--native` always includes graal and I didn't see much reason to have a 3rd build (jvm-ce).

**Comment by eregon** [comment]
Merged in https://github.com/oracle/truffleruby/commit/07d62320c0d83efd6f7f99a805d6f61d1e03d60d

I think we can close this.
Of course, we can further enhance it later.

FWIW, I tried to run `jt test integration` but that depends on the gem-test-pack for some Bundler test, and the safepoints test is quite slow (1min).

One trade-off I realized to run `test/truffle/compiler/compile-immediately.sh` on native is that it compiles less methods, due to pre-initialization. We could disable preinitialization for that test explicitly so it does the full initialization + `puts` in all cases.

**Comment by eregon** [comment]
Something else I wanted to mention, https://github.com/actions/upload-artifact is unfortunately quite slow, it takes >1min to upload a single ~200MB file: https://github.com/oracle/truffleruby/runs/1652096061
I'll file an issue upstream, but I guess it won't be solved so soon.
