### ISSUE TITLE
Nokogiri installation fails in Travis CI due to not finding libexslt

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2221]
Full logs: https://gist.github.com/gogainda/b5e3387d597c8aef301ddafa9b3fb2ed

Failed build for reference: https://travis-ci.org/github/fog/fog-google/jobs/754261599
```
ld.lld: error: unable to find library -llibexslt
```

**Comment by eregon** [comment]
This seems a new error, related to not finding libexslt.
I'm not sure what libexslt is, is it related to libxslt?

@flavorjones Could you clarify if libexslt is a new dependency of nokogiri (is it needed to build, or optional), or if the check in the extconf.rb got stricter recently?

libexslt seems typically part of the same package as libxslt (`libxslt-dev` on Debian-based, `libxslt-devel` on RedHat-based).
Locally on Linux I can install nokogiri 1.11.1 just fine.

I think this might be a bug of TravisCI shipping an incomplete libxslt package, because we see things like:
```
"/home/travis/.rvm/rubies/truffleruby-head/lib/sulong/native/bin/graalvm-native-clang
-o conftest -I/home/travis/.rvm/rubies/truffleruby-head/lib/cext/include
-I/home/travis/.rvm/rubies/truffleruby-head/lib/cext/include/ruby/backward
-I/home/travis/.rvm/rubies/truffleruby-head/lib/cext/include -I.
-I/usr/include/libxml2      -Wimplicit-function-declaration -Wno-int-conversion
-Wno-int-to-pointer-cast -Wno-incompatible-pointer-types
-Wno-format-invalid-specifier -Wno-format-extra-args -ferror-limit=500 -g
-Winline -Wmissing-noreturn  conftest.c  -L.
-L/home/travis/.rvm/rubies/truffleruby-head/lib  -rpath
/home/travis/.rvm/rubies/truffleruby-head/lib/sulong/native/lib     -lxslt
-lxml2 -lz  -lxml2 -L/home/travis/.rvm/rubies/truffleruby-head/lib/cext -rpath
/home/travis/.rvm/rubies/truffleruby-head/lib/cext -ltruffleruby -lgraalvm-llvm
-lexslt -lxslt -lxml2 -lz  -lxml2  "
ld.lld: error:
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../x86_64-linux-gnu/libxslt.so:
undefined reference to fmod
ld.lld: error:
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../x86_64-linux-gnu/libxslt.so:
undefined reference to pow
ld.lld: error:
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../x86_64-linux-gnu/libxslt.so:
undefined reference to floor
clang-10: error: linker command failed with exit code 1 (use -v to see
invocation)
```
in the log, and that sounds like that libxslt.so is quite broken, i.e., it doesn't even link to `-lm` on Linux.

This ran on Ubuntu Xenial 16.04, which is quite old.
@gogainda Could you try with Ubuntu 18.04 or 20.04 in TravisCI if that fixes it?

TravisCI is basically unusable nowadays, so not sure how much it's worth investigating vs saying "TravisCI no longer works".

**Comment by flavorjones** [comment]
I'd suggest closing this, no requirements changes have been made re: libexslt in many years, so I think this is environmental with the Travis images.

**Comment by eregon** [comment]
Thanks for the reply, agreed, this looks like a broken libxslt on TravisCI.

Using the libxslt vendored with nokogiri should solve this (tracked in https://github.com/oracle/truffleruby/issues/1974#issuecomment-776774676).

**Comment by eregon** [comment]
This should work fine now since TruffleRuby (-head and the next release) now uses the packages libraries for nokogiri since https://github.com/oracle/truffleruby/commit/dfc60c65747bab004a0c0979a9677a3075b20858
