### ISSUE TITLE
Unexpected ArgumentError when calling method and splatting empty hash

### ISSUE THREAD

**Issue by ivoanjo** [oracle/truffleruby#2260]
Hello there!

While investigating a CI failure related to the newest version of the sucker_punch gem in as part of DataDog/dd-trace-rb#1369 I spotted two behavior differences between MRI and TruffleRuby (as well as JRuby -- filed jruby/jruby#6564 with a similar description)

### Testcase 1:

```ruby
puts RUBY_DESCRIPTION
kwargs = {}
def foo
end
foo(**kwargs)
puts "Works!"
```

Behavior with TruffleRuby:

```
truffleruby 21.0.0.2, like ruby 2.7.2, GraalVM CE Native [x86_64-darwin]
splat-bug-1.rb:3:in `foo': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from splat-bug-1.rb:5:in `<main>'
```

Behavior with MRI:

```
$ ruby splat-bug-1.rb
ruby 2.4.10p364 (2020-03-31 revision 67879) [x86_64-darwin19]
splat-bug-1.rb:3:in `foo': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from splat-bug-1.rb:5:in `<main>'
$ ruby splat-bug-1.rb
ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-darwin19]
Works!
$ ruby splat-bug-1.rb
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
Works!
$ ruby splat-bug-1.rb
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
Works!
$ ruby splat-bug-1.rb
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]
Works!
```

For the life of me, I cannot find any references to a change in behavior in 2.5 for this, so perhaps it was a side-effect of some fix, rather than something deliberate.

### Testcase 2:

As a bonus, while trying to create a reduced test case for the issue, I found a second behavior that also differs in TruffleRuby, but that seems to have been changed back in MRI 2.2:

```ruby
puts RUBY_DESCRIPTION
def foo; end
foo(**{})
puts "Works!"
```

Behavior with TruffleRuby:

```
truffleruby 21.0.0.2, like ruby 2.7.2, GraalVM CE Native [x86_64-darwin]
splat-bug-2.rb:2:in `foo': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from splat-bug-2.rb:3:in `<main>'
```

Behavior with MRI:

```
$ ruby splat-bug-2.rb
ruby 2.1.10p492 (2016-04-01 revision 54464) [x86_64-darwin19.0]
splat-bug-2.rb:2:in `foo': wrong number of arguments (1 for 0) (ArgumentError)
	from splat-bug-2.rb:3:in `<main>'
$ ruby splat-bug-2.rb
ruby 2.2.10p489 (2018-03-28 revision 63023) [x86_64-darwin19]
Works!
$ ruby splat-bug-2.rb
ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-darwin19]
Works!
$ ruby splat-bug-2.rb
ruby 2.4.10p364 (2020-03-31 revision 67879) [x86_64-darwin19]
Works!
$ ruby splat-bug-2.rb
ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-darwin19]
Works!
$ ruby splat-bug-2.rb
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
Works!
$ ruby splat-bug-2.rb
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
Works!
$ ruby splat-bug-2.rb
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]
Works!
```

**Comment by eregon** [comment]
Interesting that the first example works in 2.5 and 2.6, I would expect it only works in Ruby 2.7+.
You'll notice it's also inconsistent with `def foo(*args); args; end` as that shows `[{}]` on CRuby <= 2.6, and `[]` on CRuby 2.7+.

In CRuby 2.7+, `**empty_hash` passes nothing.
`**{}` is special and removed by the parser in CRuby, which is generally considered a bug/confusing but now with Ruby 2.7+ semantics it's consistent.

TruffleRuby, on purpose, keeps the semantics of `**empty_hash` like in Ruby 2.6, so it passes it.
This is something we plan to change for Ruby 3.0, and not in 2.7, because it would be a large effort that would likely be handled quite differently in 3.0.

The real issue here is [incorrect delegation](https://eregon.me/blog/2021/02/13/correct-delegation-in-ruby-2-27-3.html) used in https://github.com/brandonhilkert/sucker_punch/pull/235.

**Comment by ivoanjo** [comment]
Thanks for looking into this @eregon! Indeed I was about to ping them about the issue as well but you beat me to it :D

**Comment by eregon** [comment]
Fixed upstream.

**Comment by eregon** [comment]
FYI, TruffleRuby now fully implements Ruby 3 keyword arguments (since b8086afe6ecc64a78e1f80f42d4ae9c05cf56605)
