### ISSUE TITLE
Keyword argument hash doesn't allocate a new hash in caller

### ISSUE THREAD

**Issue by wildmaples** [oracle/truffleruby#2282]
## Issue overview

The behaviour of `**hsh`, the double-splatted/keyword argument, is different between MRI and TruffleRuby.  

A new hash is allocated on the caller side when `m(**hsh)` is used in MRI, while TruffleRuby still uses the same `hsh` variable from the callee. 

Because of that, any modifications to `hsh` within the method is then reflected in the original `hsh` variable in TruffleRuby, which is not the intended behaviour. We found this from a failing `storefront-renderer` test. 

## Example

Let's take the method `m` that has an `options` parameter, and deletes `:hi` key from `options`. 

```ruby
def m(options = {})
  puts options.object_id
  options.delete(:hi)
end
```

And a hash, `hsh`

```ruby
hsh = {:hi => "hi", :bye => "bye"}
```

### Behaviour in MRI 

Let's start with an irb example in MRI: 

```ruby
irb(main):007:0> hsh.object_id
=> 180
irb(main):008:0> m(hsh)
180 # Same object_id without ** operator
=> "hi"
irb(main):009:0> m(**hsh)
200 # Different object_id with ** operator
=> nil

...

irb(main):013:0> hsh
=> {:hi=>"hi", :bye=>"bye"} # Original hsh is not modified
```

### Behaviour in TruffleRuby

```ruby
irb(main):006:0> hsh.object_id
=> 333432
irb(main):007:0> m(hsh)
333432 # Same object_id without ** operator ✅
=> "hi"
irb(main):008:0> m(**hsh)
333432 # Still the same object_id despite using ** operator ⛔️
=> nil

...

irb(main):009:0> hsh
=> {:bye=>"bye"} # Sure enough, the original hsh is modified! ⛔️
```

## Solutions / Next steps 

I have a spec I'll put up for PR. 

As for fixes, I haven't looked into the code yet - any ideas on where to start?

**Comment by bjfish** [comment]
This looks similar to internal issue: GR-28746

On the MRI side, I think it might be the following implementation:
https://github.com/ruby/ruby/blob/bad623558eafde1f2ea23d27afdfa6b1690ee16f/compile.c#L4265

**Comment by eregon** [comment]
Indeed, so `**h` (the caller-side `**`) should make a copy `h`.
Caller-side `**` is handled here: https://github.com/oracle/truffleruby/blob/eba171ee93c0463ab7fe193680a9d383b5ce6f7d/src/main/java/org/truffleruby/parser/BodyTranslator.java#L1841

I wonder if this is something I accidentally broke with this optimization: d00685be063b8e84932323dccdf4c26a6a6ef33d

We only need the copy for the case of `foo(**h)`, for `foo(a: 1, **h)` there is no need since we'll create a new Hash to merge them anyway.

**Comment by chrisseaton** [comment]
> Indeed, so **h (the caller-side **) should make a copy of h.

Phew... caller-side copies are better!

**Comment by wildmaples** [comment]
I've found that MRI Ruby 3.0 seems to have removed the behaviour described in this issue - https://github.com/ruby/ruby/pull/2945

> This commit makes passing a single keyword splat to a method not
allocate a hash on the caller side.

How would we approach this? TruffleRuby is on 2.7 right now and presumably, we'd want to be on 3.0 eventually. When that happens, would we just revert the fix for this issue?

**Comment by eregon** [comment]
I think that PR does not intend to change that behavior, but maybe it does.
At least 2.7.2, 3.0.0, CRuby master and current TruffleRuby still make a copy for
`ruby -e 'def self.y(**kw) kw end; h = {a:1}; p h.object_id; p y(**h).object_id'`.
But indeed 3.0.0, CRuby master and current TruffleRuby do not make a copy for:
`ruby -e 'def self.y(kw) kw end; h = {a:1}; p h.object_id; p y(**h).object_id'`.

What's special about this case is the caller is using `**` "wrongly" to call a method not accepting keyword arguments.
In other words, `foo(**h)` can probably be replaced with just `foo(h)` on the caller side, or `foo(h.dup)` if the copy is needed.
I would recommend fixing that where you found the issue because it will break on Ruby 3 and it seems a mistake anyway to use `**` in that case.

> How would we approach this? TruffleRuby is on 2.7 right now and presumably, we'd want to be on 3.0 eventually. When that happens, would we just revert the fix for this issue?

Yes, we can just do that, and the spec for 3.0 will be helpful to remember it :)
It's a bit unclear for me if worth fixing since such code is broken on Ruby 3 anyway, but it does help compatibility with 2.7.

**Comment by wildmaples** [comment]
Thanks for taking over on the specs, @eregon , I didn't get a chance to work on it after I had read your comments and reacted 😛 

> I would recommend fixing that where you found the issue because it will break on Ruby 3 and it seems a mistake anyway to use ** in that case.

I also agree that it might not be worth fixing in TruffleRuby if the behaviour is soon to be removed in Ruby 3.0 anyway. 

So I took your recommendation and decided to make a PR to fix this root `m(**hsh)` issue on the `master` branch of SFR and `.dup` the hash variable.  

In any case, I suppose having the spec will still be useful.
