### ISSUE TITLE
Installing the pg gem requires libpq-dev

### ISSUE THREAD

**Issue by petenorth** [oracle/truffleruby#2296]
`gem install pg` requires `libpq-dev` to be installed.

Recently changes in TruffleRuby enabled the `nokogiri` gem to be installed without requiring the `libxml2-dev` and `libxslt-dev` to be installed.

Should it be possible to have the `pg` gem to 'just work'?

In terms of installing gems I can now use the `flavorjones/truffleruby:nightly-buster-slim` Docker image as a base for a rails project that accesses postgres apart from needing to install the `libpq-dev` package (plus git and curl for project specific reasons).

**Comment by eregon** [comment]
No, this is the same as for CRuby, installing `pg` on any Ruby requires `libpq-dev`:
https://github.com/ged/ruby-pg#label-Requirements
I also just checked and without `libpq-dev` it fails to install on CRuby too.

Nokogiri by default on CRuby and now on TruffleRuby downloads and builds its own vendored/packaged version of libxml/libxslt (https://nokogiri.org/tutorials/installing_nokogiri.html#installing-using-the-packaged-libraries).
Due to that, those system packages are not needed.
What changed is TruffleRuby would before force using the system libraries for nokogiri, because other options didn't work.

Using vendored/packaged libraries wouldn't work for `pg`, because it needs to interact with the system-installed database and have the right version for headers, and not build its own postgres DB under the GEM_HOME.
