### ISSUE TITLE
savon gem test failure: ArgumentError: unknown keyword: code

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2298]
```
Savon::Operation.create with a WSDL raises if the endpoint cannot be reached
     Failure/Error:
       expect { new_operation(:verify_address, wsdl, globals) }.
         to raise_error(Savon::HTTPError, /#{message}/)
     
       expected Savon::HTTPError with message matching /Error!/, got #<ArgumentError: unknown keyword: code> with backtrace:
         # <internal:core> core/kernel.rb:686:in `raise'
         # ./lib/savon/operation.rb:34:in `ensure_exists!'
         # ./lib/savon/operation.rb:22:in `create'
         # ./spec/savon/operation_spec.rb:22:in `new_operation'
         # ./spec/savon/operation_spec.rb:55:in `block (4 levels) in <top (required)>'
         # ./spec/savon/operation_spec.rb:55:in `block (3 levels) in <top (required)>'
```
This is the place where issue appears:
```ruby
def self.ensure_exists!(operation_name, wsdl)
      unless wsdl.soap_actions.include? operation_name
        raise UnknownOperationError, "Unable to find SOAP operation: #{operation_name.inspect}\n" \
                                     "Operations provided by your service: #{wsdl.soap_actions.inspect}"
      end
    rescue Wasabi::Resolver::HTTPError => e
      raise HTTPError.new(e.response)
    end
```

**Comment by eregon** [comment]
Interesting, it's because HTTPError implements `to_hash`:
https://github.com/savonrb/savon/blob/0bf2a70b9c788fdef32156fad7537fc7ca46ad29/lib/savon/http_error.rb#L22-L24

@bjfish so `raise` must not use `cause:` or `**kwargs` but it needs to only take positional arguments, and then extract the `cause:` if the last arg is a Hash and has a `cause` key (we should check how MRI decides that).

This is something that will be cleaner in Ruby 3 because then we could see `HTTPError.new(e.response)` is a positional argument and not keywords. But I think we need to workaround in 2.7 to avoid this issue, like MRI 2.7 must do as well.

**Comment by bjfish** [comment]
@gogainda This is now fixed at https://github.com/oracle/truffleruby/commit/310f0550b8cada1c89e2172182c7ab63e5014d58.
