### ISSUE TITLE
Interpolated string literals aren't frozen

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#2303]
```ruby
# frozen_string_literal: true
p "foo #{14}".frozen?
```

MRI: `true`, TruffleRuby: `false`.

Found by @tomstuart in Shopify's codebase. @kirs is looking at fixing it as a beginner issue so please don't gazump his efforts.

**Comment by chrisseaton** [comment]
This should probably be specified in RubySpec but possibly isn't https://github.com/oracle/truffleruby/blob/master/spec/ruby/language/string_spec.rb (I haven't looked yet myself.)

**Comment by bjfish** [comment]
@chrisseaton @kirs This example will also change in `3.0.0` to `false`:
https://docs.ruby-lang.org/en/3.0.0/doc/syntax/comments_rdoc.html#label-frozen_string_literal+Directive

**Comment by eregon** [comment]
Yes, CRuby changed that for 3.0.
There is no much point to freeze interpolated strings literals since they can't be deduplicated at parse time.
Does it cause any compatibility issue?

I think it's not worth fixing, because it would likely break many things in core files that rely on them not being frozen, for probably very little value.

**Comment by eregon** [comment]
I forgot I'm actually the person that did this change in CRuby: https://github.com/ruby/ruby/pull/3488 :D
There are already specs for this, see that PR.

**Comment by tomstuart** [comment]
Here’s the problem:

```
# frozen_string_literal: true

frozen_string = "foo #{14}"
thawed_string = +frozen_string
thawed_string << 'bar'
puts frozen_string
```

MRI prints `foo 14` (and leaves the original string alone), TruffleRuby prints `foo 14bar` and unexpectedly mutates the original.

**Comment by eregon** [comment]
@tomstuart Thanks for the example. It's also `foo 14bar` on CRuby 3.0.

`String#+@` is incorrectly used here, it might return the receiver, if one wants a safe copy, they need `String#dup` instead.
Could you check if it makes sense fixing the application since anyway this would break in 3.0 and it seems an incorrect usage of `String#+@`?

**Comment by chrisseaton** [comment]
It took us a day to find this issue - it shows up as flakiness because it depends on the order specs are run due to the modification of the original string. We have some other flakiness elsewhere that could be the same cause. We'll see if we're able to fix without a huge diff on our core.
