### ISSUE TITLE
Support Fiber#raise after Fiber#transfer

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#2342]
See https://github.com/oracle/truffleruby/issues/2338#issuecomment-831213756
@bjfish Could you try to implement that?
That's a Ruby 3 change, so we should add the spec in `:next`.

It does mean we'll need to mark as failing this spec:
https://github.com/ruby/ruby/pull/3795/files#diff-184b163e2d8d9c8d74755a749a8d21df6692d2af454e60d3a747fcc18cfbc2faR81
but I think that's fine, probably nothing relies on that exception.

**Comment by ioquatix** [comment]
`Fiber#raise` should use transfer if the fiber was previously transferred out. At least, that's my understanding of how it works currently in Ruby 3.x.

**Comment by bjfish** [comment]
I think this is implemented since the spec/test here are passing:
https://github.com/ruby/ruby/pull/3795/files#diff-184b163e2d8d9c8d74755a749a8d21df6692d2af454e60d3a747fcc18cfbc2faR81

Additional fiber transfer for Ruby 3 was implemented here:
https://github.com/oracle/truffleruby/commit/d59b3fb70a8b125335a75a06963c2b772ab6f076

Additional Ruby 3 Fiber methods are still work in progress as tracked here:
https://github.com/oracle/truffleruby/issues/2453
