### ISSUE TITLE
Expose an interface to get compilation queue size

### ISSUE THREAD

**Issue by ChillingHsu** [oracle/truffleruby#2396]
I'm a Java newbie, and I want to fetch compilation queue size data in every iteration of my benchmark, like `Truffle::Graal.compliation_queue_size`.

To do that, I added this snippet into the class `TruffleGraalNodes` (and relevant imports):
```java
    @CoreMethod(names = "compilation_queue_size", onSingleton = true)
    public abstract static class CompilationQueueSize extends CoreMethodNode {
        @TruffleBoundary
        @Specialization
        protected int compilationQueueSize() {
            return GraalTruffleRuntime.getRuntime().getCompilationQueueSize();
        }
    }
```

and I run `jt build --env jvm-ce --name modified`, everything seems fine. but it fails when I tried to use it:
`jt -u modified ruby -e 'Truffle::Graal.compilation_queue_size'`
the error says:
```
class org.truffleruby.extra.TruffleGraalNodes$CompilationQueueSize (in unnamed module @0x39ed3c8d) cannot access class org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime (in module jdk.internal.vm.compiler) because module jdk.internal.vm.compiler does not export org.graalvm.compiler.truffle.runtime to unnamed module @0x39ed3c8d (java.lang.IllegalAccessError)
```
it appears to be the result of the Java module system, and to solve it I may have to change the module export configuration in the Graal source and recompile it. But I'm not sure about my judgement. Is there any smart approach to my purpose?

Thanks.

**Comment by eregon** [comment]
Essentially the TruffleRuby codebase cannot refer to GraalTruffleRuntime-specific classes, because it needs to be able to build with the DefaultTruffleRuntime too (used for testing and in TruffleRuby development).
So if you want to be able to access the compilation queue size from inside Ruby code, you would need to suggest adding TruffleRuntime#getCompilationQueueSize() at https://github.com/oracle/graal/issues/.

You can however see the compilation queue size with --engine.TraceCompilationDetails.
It's of course also possible to analyze this output if you just need for some experiment.

**Comment by eregon** [comment]
I'll close this because I don't think we can do anything in truffleruby, without first a change in TruffleRuntime. Or `--engine.TraceCompilationDetails` might be enough for you, and then there is no need to change anything.

**Comment by chrisseaton** [comment]
@fniephaus how do you get the queue size in your language? Do you modify Graal to do it?

**Comment by fniephaus** [comment]
In TruffleSqueak, we do [this](https://github.com/hpi-swa/trufflesqueak/blob/62c0e77654a44b2b6fe5b69286175408f0ab745f/src/de.hpi.swa.trufflesqueak/src/de/hpi/swa/trufflesqueak/nodes/plugins/TruffleSqueakPlugin.java#L62). We use our own [`JavaObjectWrapper`](https://github.com/hpi-swa/trufflesqueak/blob/62c0e77654a44b2b6fe5b69286175408f0ab745f/src/de.hpi.swa.trufflesqueak/src/de/hpi/swa/trufflesqueak/interop/JavaObjectWrapper.java) instead of Truffle's `HostObject` for accessing private/protected fields and methods. Under JDK 11+, we need to do [one more thing](https://github.com/hpi-swa/trufflesqueak/blob/62c0e77654a44b2b6fe5b69286175408f0ab745f/mx.trufflesqueak/mx_trufflesqueak.py#L44) to make things work.
For an exploration platform such as TruffleSqueak, these tradeoffs are ok. I'm not so sure you want to do the same in TruffleRuby though.

BTW: you could also apply polyglot programming and access the compilation queue through Smalltalk 🙃:
```bash
$ polyglot --shell --jvm --vm.-add-opens=jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime=ALL-UNNAMED
GraalVM MultiLanguage Shell 21.1.0
Copyright (c) 2013-2020, Oracle and/or its affiliates
  Ruby version 2.7.2
  Squeak/Smalltalk version 21.2.0-dev
js> ruby>
ruby> graal_runtime = Polyglot.eval('smalltalk', 'Graal runtime')
JavaObject[org.graalvm.compiler.truffle.runtime.hotspot.libgraal.LibGraalTruffleRuntime]
ruby> graal_runtime.getCompileQueue
JavaObject[org.graalvm.compiler.truffle.runtime.hotspot.AbstractHotSpotTruffleRuntime$Lazy]
ruby> graal_runtime.getCompileQueue.getQueueSize
0
```
