### ISSUE TITLE
`Process.spawn` does not pickup a custom `PATH` given as `ENV`

### ISSUE THREAD

**Issue by deivid-rodriguez** [oracle/truffleruby#2419]
The following script:

```ruby
require "fileutils"
require "tmpdir"

tmpdir = Dir.mktmpdir("mybin")

File.write("#{tmpdir}/foo", "#!/usr/bin/env ruby")
FileUtils.chmod("+x", "#{tmpdir}/foo")

Process.spawn({ "PATH" => [tmpdir, ENV["PATH"]].join(File::PATH_SEPARATOR) }, "foo")
```

succeeds on CRuby but prints the following error on truffleruby:

```
$ ruby repro.rb
<internal:core> core/truffle/process_operations.rb:434:in `spawn': No such file or directory - No such file or directory - foo (Errno::ENOENT)
	from <internal:core> core/truffle/process_operations.rb:84:in `spawn'
	from <internal:core> core/process.rb:672:in `spawn'
	from repro.rb:9:in `<main>'
```

**Comment by eregon** [comment]
Thank you for the report.

`posix_spawnp()` is used in TruffleRuby for spawn/system/backticks, and that searches the PATH but it seems to ignore the `PATH` variable in the `envp` passed it.
That is
https://github.com/oracle/truffleruby/blob/0c3745e48357904295877750d6e1bee87b4c8c9c/src/main/c/truffleposix/truffleposix.c#L524
ignores whether `PATH` is set in `envp` or not.

So that leaves two choices:
* We go through [`spawn-helper`](https://github.com/oracle/truffleruby/blob/0c3745e48357904295877750d6e1bee87b4c8c9c/src/main/c/spawn-helper/spawn-helper.c), and that does the `execvp()` after the env is set, when `PATH` is set in `env`.
* We do the search in PATH ourselves, and use `posix_spawn()` instead.
