### ISSUE TITLE
IO#write multiple arguments

### ISSUE THREAD

**Issue by carlhoerberg** [oracle/truffleruby#2501]
Cruby/jruby supports multiple arguments to `IO#write`, and is then using `writev` instead of `write` (for IO's who support `writev`, not all does, eg. openssl sockets). Truffleruby only supports a single argument. 

```ruby
File.open("/tmp/a", "w") do |f|
  f.write("foo", "bar", "\n")
end
```

```
<internal:core> core/io.rb:2378:in `write': wrong number of arguments (given 3, expected 1) (ArgumentError)
        from wv.rb:2:in `block in <main>'
        from <internal:core> core/io.rb:695:in `open'
        from wv.rb:1:in `<main>'
```

**Comment by eregon** [comment]
Thank you for the report, `IO#write` supports multiple arguments since Ruby 2.5 but it seems that was not yet implemented on TruffleRuby.

Given the Strings are typically in managed memory and need to be copied to native memory (at least on JVM, on SVM we could pin the `byte[]`), it's probably good enough to just add all strings together initially, copy them to native and do the write syscall.

@bjfish Could you implement it?
