### ISSUE TITLE
After debugging and modifying the source code, how to replace the current running code？

### ISSUE THREAD

**Issue by YU5Z8X2CvH1fv4ep** [oracle/truffleruby#2525]
After modifying the debugged code in chromedebuger  during debugging
, how to replace the current running code？

**Comment by eregon** [comment]
I'm not sure what you mean.
Can one even edit code in the Chrome Debugger?
If so, you'd need to save the file, and to relauch truffleruby from the command line.

Because it's Ruby it's also possible to change methods and eval code which redefines the method, but I expect the chrome debugger does not have builtin support for that besides being able to eval a snippet of code.

Does that answer your question?

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> I'm not sure what you mean. Can one even edit code in the Chrome Debugger? If so, you'd need to save the file, and to relauch truffleruby from the command line.
> 
> Because it's Ruby it's also possible to change methods and eval code which redefines the method, but I expect the chrome debugger does not have builtin support for that besides being able to eval a snippet of code.
> 
> Does that answer your question?

Can the source code be modified during debugging and then the call stack can be restarted? Do you know Java's hot code replacement feature?

**Comment by eregon** [comment]
Editing files in the Chrome Inspector/Debugger does not seem supported yet, when I edit the file and try to save it I get:
![Screenshot from 2021-11-12 09-55-35](https://user-images.githubusercontent.com/168854/141439525-c1b89ed4-413c-4d84-a45c-d9e81570fb09.png)
In any case I would never expect that to work for the current session, because saving the file would only affect the next run, like a regular text editor.

Eval'ing a method definition does override the given method, there is no need for "hot code replacement" in Ruby, it's already part of the language to be able to redefine any method.

I'm not sure what's the recommended way to eval code in the Chrome Debugger.
I found that adding a `Watch` with e.g. `def foo; 7; end` does work.
So if my script is:
```ruby
def foo
  2 * 3
end

p foo
p foo
```
and between the two prints I add the watch I get `6` and `7`.

I don't think there is a way to restart or drop frames in the Chrome Debugger (I see no UI for it at least).

In general the Chrome Debugger feels quite limited, debugging in VSCode seems more complete, see https://www.graalvm.org/tools/dap/

@entlicher might be able to tell more.

**Comment by eregon** [comment]
Using VS Code works well, one can simply eval code by using the `DEBUG CONSOLE` tab:
![Screenshot from 2021-11-12 10-13-13](https://user-images.githubusercontent.com/168854/141441834-087bb371-b89f-4972-a23e-35e8cce3aa9d.png)

I think that answers your questions so I'll mark this issue as closed.
Feel free to ask further if it's not clear though. In that case, please provide an example and explain precisely what you would like to do.
