### ISSUE TITLE
when i call java object,how can i get code complete?

### ISSUE THREAD

**Issue by YU5Z8X2CvH1fv4ep** [oracle/truffleruby#2527]
when i call java object,how can i get code complete? my ide is vscode.

like this.
```ruby
Java.import 'javax.swing.JFrame'
Java.import 'javax.swing.JLabel'

def show()
frame = JFrame.new("Window")
label = JLabel.new("Hello")
frame.xxxx  # I cant  get  'javax.swing.JFrame' class funtions !
end
```

![image](https://user-images.githubusercontent.com/57204004/141400981-59b3dde6-f6bd-4bcc-8035-d5c6cd1cf21b.png)

please help me , thanks !

**Comment by eregon** [comment]
Does https://www.graalvm.org/tools/vscode/graalvm-extension/#ruby-language-server work for you?
I think you need the language server and probably solargraph too for completion to work.

@entlicher what are the requirements for completion to work (based on runtime information)?

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> Does https://www.graalvm.org/tools/vscode/graalvm-extension/#ruby-language-server work for you? I think you need the language server and probably solargraph too for completion to work.
> 
> @entlicher what are the requirements for completion to work (based on runtime information)?

I want to get the function in the java object in ruby code

**Comment by eregon** [comment]
> I want to get the function in the java object in ruby code

`foreign.methods` already lists foreign methods, in addition to Ruby methods available on it.
So you can `puts frame.methods` to set the list.
Did you install solargraph, does completion work on regular Ruby objects?

(and `foreign.instance_variables` lists the fields of the foreign object.)

**Comment by eregon** [comment]
I can reproduce the issue.

After installing the solargraph extension, and then `gem install solargraph` on truffleruby and in the solargraph settings set the `Solargraph: Command Path` to an absolute path to `.../bin/solargraph` next to `bin/truffleruby`, then Ruby completion works.

However when trying to complete `frame.m` it fails.

I suspect solargraph doesn't trust overrides of `#methods`, but that's just a guess.

**Comment by eregon** [comment]
`foreign.method(name)` is not supported yet, but we could probably add support for that.
I guess solargraph wants to know the name of the module where the method is define for instance.

**Comment by eregon** [comment]
It seems the GraalVM LSP support could handle this.
However for host interop specifically it seems difficult, because the way completion works is it runs in a Context with basically no permissions, including no access to host interop.

Static analysis might work for this particular case, but it would need some work in solargraph.

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> It seems the GraalVM LSP support could handle this. However for host interop specifically it seems difficult, because the way completion works is it runs in a Context with basically no permissions, including no access to host interop.
> 
> Static analysis might work for this particular case, but it would need some work in solargraph.

It makes sense to complete the code at the compilation stage. Completion is very important for this project. If the IDE cannot provide a comfortable and smooth development process, truffleruby will be difficult to popularize. Truffleruby is a great project, I hope this problem can be Fix it as soon as possible, thanks to truffleruby team

**Comment by eregon** [comment]
> It makes sense to complete the code at the compilation stage.

What do you mean by compilation stage?

I see only two approaches for code completion: static analysis like solargraph does, or actually running the program in a sandbox, which I think the GraalVM LSP can do.
The second approach seems problematic here, because e.g., you wouldn't want a JFrame to pop up on screen when doing code completion (and it won't since host interop is not allowed, but it could if host interop is allowed).

So the static analysis approach seems better, and that needs work in Solargraph for VSCode. Any help there is appreciated.
Having support for this in IntelliJ/RubyMine would also be nice (would need to file that as a feature request), and IntelliJ already has some support for e.g. embedded snippets of other languages.

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> > It makes sense to complete the code at the compilation stage.
> 
> What do you mean by compilation stage?
> 
> I see only two approaches for code completion: static analysis like solargraph does, or actually running the program in a sandbox, which I think the GraalVM LSP can do. The second approach seems problematic here, because e.g., you wouldn't want a JFrame to pop up on screen when doing code completion (and it won't since host interop is not allowed, but it could if host interop is allowed).
> 
> So the static analysis approach seems better, and that needs work in Solargraph for VSCode. Any help there is appreciated. Having support for this in IntelliJ/RubyMine would also be nice (would need to file that as a feature request), and IntelliJ already has some support for e.g. embedded snippets of other languages.

I mean static analysis. Haha, sorry, my first language is not English.
