### ISSUE TITLE
how can i use TruffleRubyScriptEngine?

### ISSUE THREAD

**Issue by YU5Z8X2CvH1fv4ep** [oracle/truffleruby#2538]
what is org.truffleruby.services.scriptengine.TruffleRubyScriptEngine.class ? i cant find it Constructor . how can i use TruffleRubyScriptEngine? is there any help docment?

![image](https://user-images.githubusercontent.com/57204004/142963299-52faa224-b8db-4d34-bf94-710fbac30d27.png)

**Comment by eregon** [comment]
It's meant to be used like a ScriptEngine: https://docs.oracle.com/javase/8/docs/technotes/guides/scripting/prog_guide/api.html
You should not attempt to instantiate it yourself but use `ScriptEngineManager#getEngineByName("ruby")`.

The Context/Engine API is much preferred though, so please use that instead.
That's documented on https://www.graalvm.org/.
We might remove TruffleRubyScriptEngine in future releases, since it does not offer enough flexibility.

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> It's meant to be used like a ScriptEngine: https://docs.oracle.com/javase/8/docs/technotes/guides/scripting/prog_guide/api.html You should not attempt to instantiate it yourself but use `ScriptEngineManager#getEngineByName("ruby")`.
> 
> The Context/Engine API is much preferred though, so please use that instead. That's documented on https://www.graalvm.org/. We might remove TruffleRubyScriptEngine in future releases, since it does not offer enough flexibility.

thanks
