### ISSUE TITLE
what is Ruby-NativeCallInterrupt-Timer 

### ISSUE THREAD

**Issue by YU5Z8X2CvH1fv4ep** [oracle/truffleruby#2555]
What is the role of Ruby-NativeCallInterrupt-Timer ? I created multiple context evals and did not use them, but I saw a lot of Ruby-NativeCallInterrupt-Timer . Will they consume my thread resources when I don’t use the context?

![image](https://user-images.githubusercontent.com/57204004/147870042-3e7269aa-d7a1-42c0-af25-0ca3750197ed.png)

**Comment by YU5Z8X2CvH1fv4ep** [comment]
In other words, will it consume a lot of my CPU resources when I don't actually use the context?

**Comment by YU5Z8X2CvH1fv4ep** [comment]
I might create 100 contexts

**Comment by chrisseaton** [comment]
They shouldn't be doing anything by default - they're just there to be able to run an interrupt if required. Are they really consuming a lot of CPU time?

But I do think we should try to consolidate our background tasks - `nfi-gc`, `Ruby-NativeCallInterrupt-Timer`, etc.

**Comment by eregon** [comment]
These threads are needed to interrupt native calls, CRuby uses the timer thread IIRC for this which is somewhat similar.
Those timer threads will be idle most of the time, they are only active when needing to interrupt a native call, e.g., if a thread is reading from a Socket and another thread interrupts it with Thread#raise, or Ctrl+C, or a signal is sent to the process.

I don't think we can easily have only have 1 of those threads per process vs 1 per Context as currently, notably because we want to terminate this thread once the Context is closed.

You can use VisualVM (shipped in GraalVM) to see what these threads do, they likely wait most of the time, and so shouldn't cause any problem.

I'll close for now, but feel free to comment here if those threads actually causes issues and I'll reopen.

**Comment by eregon** [comment]
We could create that thread lazily on the first blocking native call, that's likely to be really early though for most Ruby applications, so not sure it's worth the additional complexity.

I forgot to mention, you can disable this thread with `--platform-native-interrupt=false` but obviously then it won't be possible to interrupt native calls at all. Disabling native access on the Context.Builder (or `--platform-native=false`) would also disable it, together with disabling NFI (native calls) entirely.

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> 
thanks for your answer

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> They shouldn't be doing anything by default - they're just there to be able to run an interrupt if required. Are they really consuming a lot of CPU time?
> 
> But I do think we should try to consolidate our background tasks - `nfi-gc`, `Ruby-NativeCallInterrupt-Timer`, etc.

thanks for your answer
