### ISSUE TITLE
Pathname#glob is missing

### ISSUE THREAD

**Issue by phene** [oracle/truffleruby#2559]
Pathname's glob method is missing

**Comment by eregon** [comment]
Indeed, thanks for the report.
```
ruby -rpathname -e 'p Pathname.pwd.glob("*")'   
-e:1:in `<main>': undefined method `glob' for #<Pathname:/home/eregon> (NoMethodError)
```

(`Pathname.glob` is there though)

We should try to add Pathname to https://github.com/oracle/truffleruby/blob/master/spec/truffle/methods_spec.rb and see if any other methods are missing, and try to untag the Pathname MRI tests.

TruffleRuby's version of Pathname is unfortunately not always in sync because CRuby for rather unclear reasons moved most of Pathname to C and it doesn't make much sense to run that as a C extension. I think the longer-term solution is to move Pathname back to Ruby code in CRuby and then we can just import that (I should open a ticket on CRuby for that, maybe a PR too).

**Comment by eregon** [comment]
I found the previous CRuby discussion regarding moving Pathname back to Ruby: https://bugs.ruby-lang.org/issues/17473#note-1

**Comment by bjfish** [comment]
@phene `Pathname#glob` is now implemented here: https://github.com/oracle/truffleruby/commit/4888d8b35787f1a56a306fb7782b150110657655. Thanks!
