### ISSUE TITLE
pattern match bug with internal array

### ISSUE THREAD

**Issue by HoneyryderChuck** [oracle/truffleruby#2617]
Given truffleruby's ruby 3 support, a [new codepath was unlocked](https://gitlab.com/honeyryderchuck/httpx/-/blob/master/test/extensions/response_pattern_match.rb#L9) in httpx test suite which surfaced what it seems like a [parser bug](https://gitlab.com/honeyryderchuck/httpx/-/jobs/2168456117#L491).

This should also be easily reproducible just by copying the line with the pattern match (I did it using irb and it crashed the console).

**Comment by eregon** [comment]
Pattern matching is not implemented yet, that's why it's a SyntaxError.
It's currently tracked as part of https://github.com/oracle/truffleruby/issues/2453.
The main issue is it's a huge effort to update the parser, with no easy solution.
We're trying to figure out a better long term solution to keep the parser up-to-date with reasonable efforts (instead of copying+adapting thousands of lines manually from JRuby or CRuby).

**Comment by eregon** [comment]
Does httpx support Ruby <= 2.6 which doesn't have pattern matching? It seems so from the gemspec 7 CI files.
What does it use to detect if pattern matching is supported?
The best way is probably to check one by trying to `eval` some pattern matching and if that's SyntaxError -> not supported.

**Comment by HoneyryderChuck** [comment]
>Does httpx support Ruby <= 2.6  

It does.

The [detection is only relevant for tests](https://github.com/onfido/onfido-openapi-spec/tree/master/schemas), and is based on ruby version. For the library, the extensions are [fairly safe](https://gitlab.com/honeyryderchuck/httpx/-/blob/master/lib/httpx/pmatch_extensions.rb) even if pattern matching wouldn't be supported.

I guess I can use the `eval` as you suggested for now. It just feels a bit odd not going with the ruby version, as for other rubies it's a pretty reliable "feature discovery" tool (although I understand the issues related with the parser).

**Comment by eregon** [comment]
In general feature detection is much better than checking RUBY_VERSION (also applies to C APIs BTW), RUBY_VERSION should IMHO only be used when there is no other reasonable way (very rare).
Since TruffleRuby is released every 3 months, it's always possible some features of a CRuby version are not implemented, and so feature detection is important.

**Comment by HoneyryderChuck** [comment]
Sorry, I meant ruby version is pretty reliable **if** I can't do feature detection (i.e. `defined?(NewClass)` or `.respond_to?(:fancy_new_method)`) :-) . I guess there isn't a great way to feature-detect new syntax, besides your suggestion, so I'll take it.

**Comment by HoneyryderChuck** [comment]
Applied the patch, should this be kept open?

**Comment by eregon** [comment]
Let's close this, we have other issues to track pattern matching support, and until then the SyntaxError is expected.
