### ISSUE TITLE
Truffle crashes when trying to load large set in RAM 

### ISSUE THREAD

**Issue by tiredenzo** [oracle/truffleruby#2635]
Dear TruffleRuby team,

While trying to load a large CSV file as a Hash, with TruffleRuby I encountered some issues:

The the CSV file weighs about 39G and has 700 millions of lines.
The machine I run has 240G of RAM
TurffleRuby verison is installed via RVM `truffleruby 22.0.0.2, like ruby 3.0.2, GraalVM CE Native [x86_64-linux]`

The script runs and loads up until line ~= 129M and RAM usage is 66 Gigs when it crashes with the following error
`Fatal error: java.lang.OutOfMemoryError: Could not allocate an aligned heap chunk`
Ful log here:  https://gist.github.com/tiredenzo/088f754a716adfada26144ca3b1baff2

Issue is that RruffleRuby will not be able to use the whole machine's 240 GB RAM and will crash around 66GB load :

Please note that the same scripts will work with ruby-3, it will loads completely will take about 140/150 G of RAM with ruby-3
On a side note, I also tried loading "sharding" the data accross 10k Hashes to see if it worked better. the programm behavior was the same

To reproduce run the following

Faster (directly in RAM)
```ruby test_no_csv.rb```

Slower (use disk to generate csv before loading it)
```ruby generate_test_csv.rb && ruby load_csv.rb```

```ruby
# test_no_csv.rb

hash = {}
value = (0...40).map { ('a'..'z').to_a[rand(26)] }.join

700_000_000.times do |i|
  puts i if i % 1_000_000 == 0

  key = 1_000_000 + i
  hash[key] = "#{value}#{key}"
end
```

```ruby
# generate_test_csv.rb

output_file = File.open('test.csv', 'w')
value = (0...40).map { ('a'..'z').to_a[rand(26)] }.join

700_000_000.times do |i|
  key = 1_000_000 + i

  output_file.write("#{key},#{value}#{key}\n")
end

output_file.close
```

```ruby
# load_csv.rb

hash = {}

File.foreach('test.csv').with_index do |line, line_num|
  puts line_num if line_num % 1_000_000 == 0

  line = line.strip
  id, path = line.split(',')
  id = id.to_i

  hash[id] = path
end
````

Thank you

**Comment by eregon** [comment]
I made a script to make it clearer what is going on, please see https://gist.github.com/eregon/93523d087c283ac88d13a75845e5785e

So TruffleRuby doesn't use the full RAM by default, because the underlying VM has a default max heap which is smaller than the full RAM. However, it is possible to make it use all RAM with e.g. `--vm.Xmx240g`.

Could you try with `--vm.Xmx240g` and also try both `--native` (the default) and `--jvm`?
RVM doesn't support the `--jvm` node, so for that use
`ruby-build truffleruby+graalvm-22.0.0.2 ~/.rubies/truffleruby+graalvm-22.0.0.2`.
I think the `--jvm` mode is going to be significantly better here due to the better GC.

**Comment by tiredenzo** [comment]
Hi, thanks for your reply

I installed TruffleRuby with ruby-build as you asked. And added your script to mine, it is indeed better ;)

- For `--native` with `--vm.Xmx240g` I did not see any difference
```
# runs until line 110M
.rubies/truffleruby+graalvm-22.0.0.2/bin/ruby --vm.Xmx240g --native test_no_csv.rb

heap: 40574 MB used, 43427 MB committed, ? max, RSS: 39452 MB, allocated: ?
Fatal error: java.lang.OutOfMemoryError: Could not allocate an aligned heap chunk

https://gist.github.com/tiredenzo/9eb69eb064280f46a3a5639958940f9e
```

- For `--jvm` with `--vm.Xmx240g` sadly it did not work but it went much further. It was also blazingly fast compared to `--native`, comparable to a couple of times of the speed I reached in GoLang for this task.
```
.rubies/truffleruby+graalvm-22.0.0.2/bin/ruby --vm.Xmx240g --jvm test_no_csv.rb

# runs until line 402M
heap: 119760 MB used, 192928 MB committed, 245760 MB max, RSS: 162246 MB, allocated: ?

truffleruby: an internal exception escaped out of the interpreter,
please report it to https://github.com/oracle/truffleruby/issues.

-2147483604 (java.lang.NegativeArraySizeException)
        from org.truffleruby.core.hash.library.BucketsHashStore.resize(BucketsHashStore.java:128)
        from org.truffleruby.core.hash.library.BucketsHashStore.set(BucketsHashStore.java:264)
        from org.truffleruby.core.hash.library.BucketsHashStoreGen$HashStoreLibraryExports$Cached.set(BucketsHashStoreGen.java:141)
        from org.truffleruby.core.hash.HashNodes$SetIndexNode.set(HashNodes.java:214)
        from org.truffleruby.core.hash.HashNodesFactory$SetIndexNodeFactory$SetIndexNodeGen.execute(HashNodesFactory.java:911)
        from org.truffleruby.language.RubyCoreMethodRootNode.execute(RubyCoreMethodRootNode.java:48)
        from jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:655)
test.rb:29:in `[]='
        from test.rb:35:in `block in <main>'
        from <internal:core> core/integer.rb:148:in `times'
        from test.rb:22:in `<main>'
```

Here is my code for this test https://gist.github.com/tiredenzo/cd97f74a054d5a1c4b1b99473318920b

**Comment by aardvark179** [comment]
This looks like a bug in our hash implementation when we try to allocate very large buckets. We have an array of capacities, and then allocate an array of that capacity multiplied by a constant, and for the largest defined capacity this overflows the 32 bit array offset.

**Comment by eregon** [comment]
I will try to reproduce on native (on a machine with enough RAM), that early OutOfMemoryError sounds like a bug.

On JVM that NegativeArraySizeException we see is because of trying to create a very big Hash.
That error could be improved to be clearer.
An array in Java has a (signed) `int` size, and so the maximum is  2**31 - 1 = 2 147 483 647 elements

The Hash would have 700_000_000 pairs at the end, the max load factor is 0.75 (otherwise there is too much chaining).
So it'd need at strict minimum 700_000_000 / 0.75 = 933 333 333 elements.
That still fits in a Java array.

The current logic on resize, based on CRuby IIRC, is to pick the next capacity (1 073 741 909 here), and multiply it by 4 (OVERALLOCATE_FACTOR) so we don't have to resize too soon again. 1 073 741 909 * 4 = 4 294 967 636 which is close to 2**32 and bigger than the max Java array size.
But we could probably use a smaller OVERALLOCATE_FACTOR in that case, i.e., use an array size close to the max array size. As long as the load factor would still be < 0.75 it seems fine. If it then needs to resize up again, then we'd fail with an error.

> I kept my allocation method, this might not have been a good choice for you, I can re-run with yours if you wish

Could you try with my script as well? We should see on JVM it should be able to use all the RAM. On Native it's probably the same error but worth a try still.

**Comment by eregon** [comment]
I got access to a machine with 251GB of RAM. I used the latest truffleruby.
On my script:
```
$ ./truffleruby-21.3.2-dev-linux-amd64/bin/ruby --vm.Xmx240g --vm.XX:+PrintGC use_memory.rb 
...
heap: 237578 MB used, 237610 MB committed, ? max, RSS: 238124 MB, allocated: 237568 MB
heap: 238602 MB used, 238634 MB committed, ? max, RSS: 239138 MB, allocated: 238592 MB
[Full GC (CollectOnAllocation) 244328451K->244327427K, 0.1467810 secs]
[Full GC (CollectOnAllocation) 245376003K->245376003K, 0.0767473 secs]
heap: 239626 MB used, 239658 MB committed, ? max, RSS: 240154 MB, allocated: 239616 MB
heap: 240650 MB used, 240682 MB committed, ? max, RSS: 241177 MB, allocated: 240640 MB
[Full GC (CollectOnAllocation) 246425603K->246424579K, 0.1811087 secs]

[Full GC (CollectOnAllocation) 247473155K->247473155K, 9.3663270 secs]
heap: 241674 MB used, 241706 MB committed, ? max, RSS: 242202 MB, allocated: 241664 MB
Killed
```
So it does reach 240GB before being killed. It takes a while though.
So maybe the issue that `--native` didn't use all available memory was resolved already?

Using your `test_no_csv.rb` script:
```
$ ./truffleruby-21.3.2-dev-linux-amd64/bin/ruby --vm.Xmx240g --vm.XX:+PrintGC test_no_csv.rb 
...
heap: 21991 MB used, 22056 MB committed, ? max, RSS: 22537 MB, allocated: ?
[Incremental GC (CollectOnAllocation) 22585345K->22584321K, 11.1044361 secs]
73000000
heap: 22282 MB used, 22311 MB committed, ? max, RSS: 22792 MB, allocated: ?
[Incremental GC (CollectOnAllocation) 22846465K->22846465K, 10.5636581 secs]
[Incremental GC (CollectOnAllocation) 23108609K->23108609K, 9.4776473 secs]
74000000
heap: 22573 MB used, 22823 MB committed, ? max, RSS: 23304 MB, allocated: ?
[Incremental GC (CollectOnAllocation) 23370753K->23369729K, 9.1272530 secs]
75000000
heap: 22864 MB used, 23078 MB committed, ? max, RSS: 23560 MB, allocated: ?
[Full GC (CollectOnAllocation) 23631873K->23631873K, 94.8030409 secs]
^C
```
I was not patient enough and cancelled it after a few minutes.
The Native Image CE GC is not good enough for this.
It would likely work quite a bit better with Native Image EE GC (which is G1 for Native Image).

I'll try JVM next.

**Comment by eregon** [comment]
I've run on JVM too, and test_no_csv.rb on `--native`.
There was no problem on native, it's the same result as on `--jvm`.
Both end up with the `NegativeArraySizeException`, so I'll look into that next.

**Comment by eregon** [comment]
I've got a fix for the `NegativeArraySizeException`, and I could run a slight variant of the script to the end (https://gist.github.com/eregon/70787386138f339b964fb76496a3f1d9 it uses a little bit less memory):
```
$ ruby --jvm --vm.Xmx240g --vm.XX:+PrintGC test_no_csv.rb |& tee out.log
...
697
heap: 78752 MB used, 125472 MB committed, 245760 MB max, RSS: 105461 MB, allocated: ?
698
heap: 78848 MB used, 125472 MB committed, 245760 MB max, RSS: 105461 MB, allocated: ?
699
heap: 78912 MB used, 125472 MB committed, 245760 MB max, RSS: 105462 MB, allocated: ?
```

**Comment by tiredenzo** [comment]
thanks 👍

**Comment by eregon** [comment]
So it should work fine now. I didn't compare to CRuby (I don't have a recent CRuby on that machine).

If you want to optimize this workload to make it faster, it's probably best to avoid such a large memory usage/heap (because the GC becomes a lot slower, and growing the Hash takes a lot of time), and process e.g. line-by-line if that's possible.
Also an Array would store the entries much more compactly (and much better use of the cache) than a Hash, and might still allow to search entries fairly quickly via their `id` using `bsearch`, assuming the ids are in increasing order in the .csv file.
