### ISSUE TITLE
Error compile 'getsource-0.2.2' with <gcc: error: unrecognized command line option ‘-ferror-limit=500’>

### ISSUE THREAD

**Issue by Tiikara** [oracle/truffleruby#2678]
**OS**: Ubuntu 20.04
**Arch**: amd64
**Truffleruby version**: truffleruby+graalvm-22.1.0
**Package manager**: rbenv
**Ruby version output**: `truffleruby 22.1.0, like ruby 3.0.2, GraalVM CE JVM [x86_64-linux]`

When I run :
```
gem install shikashi
```

Got following output:

```
Fetching getsource-0.2.2.gem
Fetching sexp_processor-4.16.1.gem
Fetching ruby_parser-3.19.1.gem
Fetching ruby2ruby-2.4.4.gem
Fetching partialruby-0.3.0.gem
Fetching evalhook-0.6.0.gem
Fetching shikashi-0.6.0.gem
Building native extensions. This could take a while...
ERROR:  Error installing shikashi:
        ERROR: Failed to build gem native extension.

    current directory: /root/.rbenv/versions/truffleruby+graalvm-22.1.0/graalvm/languages/ruby/lib/gems/gems/getsource-0.2.2/ext/getsource_base
/root/.rbenv/versions/truffleruby+graalvm-22.1.0/graalvm/languages/ruby/bin/truffleruby -I /root/.rbenv/versions/truffleruby+graalvm-22.1.0/graalvm/languages/ruby/lib/mri -r ./siteconf20220614-26582-fb5c8m.rb extconf.rb
creating Makefile

current directory: /root/.rbenv/versions/truffleruby+graalvm-22.1.0/graalvm/languages/ruby/lib/gems/gems/getsource-0.2.2/ext/getsource_base
make DESTDIR\= clean

current directory: /root/.rbenv/versions/truffleruby+graalvm-22.1.0/graalvm/languages/ruby/lib/gems/gems/getsource-0.2.2/ext/getsource_base
make DESTDIR\=
compiling getsource_base.c
gcc: error: unrecognized command line option ‘-ferror-limit=500’
make: *** [Makefile:515: getsource_base.o] Error 1

make failed, exit code 2

Gem files will remain installed in /root/.rbenv/versions/truffleruby+graalvm-22.1.0/graalvm/languages/ruby/lib/gems/gems/getsource-0.2.2 for inspection.
Results logged to /root/.rbenv/versions/truffleruby+graalvm-22.1.0/graalvm/languages/ruby/lib/gems/extensions/x86_64-linux/3.0.2.22.1.1/getsource-0.2.2/gem_make.out
```

**Comment by eregon** [comment]
It's due to https://github.com/tario/getsource/blob/43417d97fb1391548659c513c257cf019e409d9b/ext/getsource_base/extconf.rb hardcoding `gcc`.
That old gem won't work on TruffleRuby anyway (it digs in private method internals), and I don't see the point of it, there is `Method#source_location` since a while, no need for a C extension to get the filename for a Method object.

The fix for this is for the [shikashi](https://github.com/tario/shikashi) gem to stop depending on [getsource](https://github.com/tario/getsource):
https://github.com/tario/shikashi/blob/171e0687a42327fa702225e8ad0d321e578f0cb0/Rakefile#L16
Could you file an issue there (or a PR) to do that?

I'll close this, it's up to the ecosystem to use core methods instead of C extensions for things like this.
