### ISSUE TITLE
require_relative incompatibility after Dir.chdir

### ISSUE THREAD

**Issue by k0kubun** [oracle/truffleruby#2709]
With the following two files, `a/b.rb` and `a/c.rb`,

```rb
# a/b.rb
puts 'b'
Dir.chdir __dir__
require_relative 'c'
```

```rb
# a/c.rb
puts 'c'
```

CRuby and TruffleRuby give different results:

```
$ ~/.rbenv/versions/3.1.2/bin/ruby -v a/b.rb
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
b
c

$ ~/.rbenv/versions/truffleruby+graalvm-22.2.0/bin/ruby -v a/b.rb
truffleruby 22.2.0, like ruby 3.0.3, GraalVM CE Native [aarch64-darwin]
b
<internal:core> core/kernel.rb:295:in `require_relative': cannot load such file -- /Users/k0kubun/tmp/truffle/a/a/c (LoadError)
        from a/b.rb:3:in `<main>'
```

Is this intentional?

**Comment by eregon** [comment]
Thanks for the report, it's not intended, we should fix it.
IIRC JRuby has the same issue.

It might not be completely trivial, because `__FILE__` in `a/b.rb` is just `a/b.rb` and conceptually `require_relative` is based on `__FILE__`, and that's why we currently see this behavior. Probably we can base it on `__dir__` or handle specially the main script path (which is the only file path which can be relative and not absolute).

This happens for yjit-bench IIRC, right? Maybe with the [run_benchmarks.rb](https://github.com/Shopify/yjit-bench/blob/main/run_benchmarks.rb) script?

IMHO it's better to run a benchmark from its directory than rely on those semantics, i.e. avoid Dir.chdir at runtime and let the caller script pass the correct working directory to start with.

**Comment by k0kubun** [comment]
> This happens for yjit-bench IIRC, right? Maybe with the [run_benchmarks.rb](https://github.com/Shopify/yjit-bench/blob/main/run_benchmarks.rb) script?

It's here https://github.com/Shopify/yjit-bench/blob/287fa7c9253068255f2e706b14f88e8fc0affa85/benchmarks/railsbench/benchmark.rb#L10. Apparently they did for running `bin/rails db:migrate db:seed`.

> avoid Dir.chdir at runtime and let the caller script pass the correct working directory to start with.

I don't have a strong preference for this one TBH, but it could be an easy workaround when we want to run TruffleRuby.

**Comment by eregon** [comment]
I have a fix for this, it should be merged soon.
