### ISSUE TITLE
IO#write does not support multiple arguments with different encodings

### ISSUE THREAD

**Issue by mhib** [oracle/truffleruby#2829]
Command to reproduce the issue:

```bash
 ruby -rtempfile -e 'p Tempfile.open { |f| f.write("\x87".b, "ą") }'
 ```
 It outputs `3` both on CRuby and JRuby, but crashes on TruffleRuby.

**Comment by eregon** [comment]
Interesting, this works because the `IO#external_encoding` is `nil` and so there is no conversion and it's just written as plain bytes.

One solution is to internally call `write` for each string, but then that's many system calls, so seems somewhat inefficient, and recursive calls are not so nice. Maybe still fine.
Might be incorrect for Fiber scheduler purposes, not sure if CRuby concatenates for that case or calls the hook for each string, that'd be worth checking.

Another solution is have some Primitive to concatenate strings without looking at the encoding, but this is only OK if IO#write is not going to do any encoding conversion, so seems a bit tricky but feasible.

**Comment by andrykonchin** [comment]
Regarding a Fiber scheduler. It looks like there are several scenarios of how CRuby writes data and calls a scheduler:

- data is written with `writev` syscall and a scheduler is called for each String argument (if `IO#sync = true` and IO internal buffer is empty)
- data is added to an IO internal buffer, a scheduler isn't called at all (if all the data fits in an IO internal buffer and this buffer already contains some data)
- data is added to an IO internal buffer, buffer + the next String argument are written with `writev` syscall and a scheduler is called for each of them **only** when buffer is full (if `IO#sync = false`)
- a String argument is written with `write` and a schedules it called for it if the String argument doesn't fit into an IO internal buffer (if `IO#sync = false` and IO internal buffer is empty)
