### ISSUE TITLE
Debug console resolving calls in incorrect scope

### ISSUE THREAD

**Issue by nirvdrum** [oracle/truffleruby#2847]
While trying to debug a native extension, I found myself in the `Truffle::CExt#rb_define_method` implementation. In there, the value `argc`, which is a function argument, is being compared to several values. `argc` does not appear in the "Variables" view in VS Code and I'm unable to evaluate it in the Debug Console. It looks like the value is being looked up in `self` rather than the module method's scope.

<img width="812" alt="image" src="https://user-images.githubusercontent.com/12584/216156246-4c685faa-7c6f-4f9a-806b-713cbca855cd.png">

**Comment by eregon** [comment]
That's because of `Truffle::Graal.copy_captured_locals`, that actually replaces local variable reads outside that lambda with their value in the AST, so `argc` (and other outer vars) does not exist as a Ruby local variable anymore (inside the lambda).
It's unfortunate for debugging, but I don't see any way to solve this without giving up on the optimization.
