### ISSUE TITLE
Add `rb_newobj` to native extension API

### ISSUE THREAD

**Issue by nirvdrum** [oracle/truffleruby#2869]
_memcached_ 1.8.0 requires the `rb_newobj` function via the `NEWOBJ` macro. #2752 implemented several new extension functions for _memcached_, but at the time I narrowed the scope down to just those used by a particular application I was trying to get running. I'm now adding some of that application's dependencies to CI with TruffleRuby and finding more functionality being exercised. It's probably worth just running the _memcached_ test suite and see what else we're missing.

**Comment by eregon** [comment]
We cannot really implement `rb_newobj()` in the general case, because that doesn't give the class and so doesn't tell us which impl class should be used (e.g. RubyDynamicObject vs RubyArray vs RubyException, etc), and we can't change the Java class of an existing object of course.
We could probably just use `RubyDynamicObject` and hope we guessed right though, if necessary.
But extensions should not use `NEWOBJ` anymore:
My understanding is `rb_newobj()` is deprecated by `rb_newobj_of()`, although it's not a compiler warning yet:
```c
/**
 * Declares, allocates, then assigns a new object to the given variable.
 *
 * @param      obj             Variable name.
 * @param      type            Variable type.
 * @exception  rb_eNoMemError  No space left.
 * @return     An allocated object, not initialised.
 * @note       Modern programs tend to use #NEWOBJ_OF instead.
 *
 * @internal
 *
 * :FIXME: Should we deprecate it?
 */
#define RB_NEWOBJ(obj,type) type *(obj) = RBIMPL_CAST((type *)rb_newobj())
```

I don't find a usage of NEWOBJ in https://github.com/search?q=repo%3Aarthurnn%2Fmemcached+RB_NEWOBJ&type=code. Could you link to the usage?

**Comment by nirvdrum** [comment]
Thanks. I hadn't looked at the semantics of that function, but I started poking at this this morning and came to a similar conclusion.

_memcached_ is in a weird state. Its last release was 1.8.0 in 2014. The _master_ branch is their pending work for 2.0, but naturally it'll take a new release and then everyone depending on 1.x to upgrade to 2.0. Consequently, you need to look at the _memcached-1.8.0_ tag. The [NEWOBJ usage is in rb_str_new_by_ref](https://github.com/arthurnn/memcached/blob/1c659c0d15bcdbd058fff89cc2a696c141011ef4/ext/rlibmemcached_wrap.c#L2253-L2277).

Now that I'm looking at it, the `rb_str_new_by_ref` function can't work in TruffleRuby even if we support `rb_newobj` as we don't have `RString`. There's an `#ifdef OBJSETUP` that has a branch for running on Rubinius and JRuby that should work. I can fix that in a fork and use that in my _Gemfile_, but that won't help anyone else trying to run the gem on TruffleRuby. Given it hasn't had a release in almost 9 years, I don't like our odds in getting a new release out with such a fix. But, hopefully I'm wrong.

@evan would you be willing to cut a new release with a small fix to get _memcached_ 1.8.x running on TruffleRuby?

**Comment by eregon** [comment]
Actually we might be able to fix this on the TruffleRuby side without a change in memcached, because the condition is `#ifdef OBJSETUP`.
And OBJSETUP is a macro defined by CRuby.
TruffleRuby currently defines that macro because we copy headers from CRuby, but we can modify them as needed.
Since TruffleRuby doesn't support NEWOBJ+OBJSETUP, but rather it supports the newer NEWOBJ_OF which does both in one step, it makes sense to not define OBJSETUP, and probably not define NEWOBJ either.
@nirvdrum Are you interested to create a PR doing that and adding a TruffleRuby C-API spec to ensure we don't define it accidentally in the future?

**Comment by nirvdrum** [comment]
Yeah, I'll open the PR. I didn't want to accidentally break other extensions that might use `OBJSETUP` to tell JRuby apart from MRI. Hopefully no one is actually doing that, but it's why I thought I'd modify the `#ifdef` in _memcached_.
