### ISSUE TITLE
NPE escaping when working with an uninitialized `SizedQueue`

### ISSUE THREAD

**Issue by nirvdrum** [oracle/truffleruby#2923]
I'm working on refreshing our tags for the MRI tests. While doing so, I ran into a situation where a `NullPointerException` is escaping into Ruby when pushing to an uninitialized `SizedQueue`. I can't imagine this is a situation that comes up often, but it does halt our `jt retag` process so it'd be nice to have resolved.

In MRI, we end up seeing a `TypeError` for working with an uninitialized `SizedQueue`:

```
> ruby -v -e 'SizedQueue.allocate.push(nil)'
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [arm64-darwin22]
-e:1:in `push': #<Thread::SizedQueue:0x0000000104f21d90> not initialized (TypeError)
        from -e:1:in `<main>'
```

Whereas in TruffleRuby it looks like we're assuming the queue has been initialized by the time operations are being run on it:

```
> jt ruby -v -e 'SizedQueue.allocate.push(nil)'
Using TruffleRuby with Graal: mxbuild/truffleruby-jvm-ce
$ /Users/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/mxbuild/truffleruby-jvm-ce/languages/ruby/bin/ruby \
  --experimental-options \
  --core-load-path=/Users/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/src/main/ruby/truffleruby \
  -v \
  -e \
  'SizedQueue.allocate.push(nil)'
truffleruby 23.0.0-dev-671182fb*, like ruby 3.1.3, GraalVM CE JVM [aarch64-darwin]

truffleruby: an internal exception escaped out of the interpreter,
please report it to https://github.com/oracle/truffleruby/issues.

Cannot invoke "org.truffleruby.core.queue.SizedQueue.put(Object)" because "queue" is null (java.lang.NullPointerException)
        from org.truffleruby.core.queue.SizedQueueNodes$PushNode.lambda$doPushBlocking$0(SizedQueueNodes.java:126)
        from org.truffleruby.core.thread.ThreadManager.lambda$runUntilResult$4(ThreadManager.java:614)
        from com.oracle.truffle.api.impl.ThreadLocalHandshake$TruffleSafepointImpl.setBlockedBoundary(ThreadLocalHandshake.java:596)
        from com.oracle.truffle.api.impl.ThreadLocalHandshake$TruffleSafepointImpl.setBlockedWithException(ThreadLocalHandshake.java:567)
        from org.truffleruby.core.thread.ThreadManager.runUntilResult(ThreadManager.java:611)
        from org.truffleruby.core.thread.ThreadManager.runUntilResult(ThreadManager.java:590)
        from org.truffleruby.core.queue.SizedQueueNodes$PushNode.doPushBlocking(SizedQueueNodes.java:125)
        from org.truffleruby.core.queue.SizedQueueNodes$PushNode.pushBlocking(SizedQueueNodes.java:118)
        from org.truffleruby.core.queue.SizedQueueNodesFactory$PushNodeFactory$PushNodeGen.executeAndSpecialize(SizedQueueNodesFactory.java:604)
        from org.truffleruby.core.queue.SizedQueueNodesFactory$PushNodeFactory$PushNodeGen.execute(SizedQueueNodesFactory.java:592)
        from org.truffleruby.language.RubyCoreMethodRootNode.execute(RubyCoreMethodRootNode.java:58)
-e:1:in `push'
        from -e:1:in `<main>'
```

**Comment by eregon** [comment]
This one is interesting.
The test is:
```ruby
  def test_sized_queue_initialized
    assert_raise(TypeError) {
      SizedQueue.allocate.push(nil)
    }
  end
```

That's basically undefined/implementation-defined behavior, it's invalid to call `allocate` and no `initialize*` after and use a method on it.

There are 3 solutions:
1. Keep this as a fatal exception, because this is very broken code anyway. And have `jt retag` not try to remove `exclude` for this, e.g. mark this as a "fatal exclude" or "broken test exclude"
2. We could do `new RubySizedQueue(rubyClass, getLanguage().sizedQueueShape, new SizedQueue(0));` in `SizedQueue.allocate`. The downside is this is extra allocations, behind a TruffleBoundary, only to support broken code. If we can share a global "frozen/closed" (Java) SizedQueue instance then it'd be OK as it wouldn't change performance. This will not match CRuby semantics and not pass this test, but it will not crash which is maybe useful.
3. Have checks in every SizedQueue method if allocated and do the same as CRuby (which is inconsistent, sometimes it's TypeError, but e.g. for closed? it's `false`, which sounds like a bug, but irrelevant since nobody should do this). This is a lot of work, very error-prone and trying to match basically broken behavior in CRuby, so not a good idea from maintainability POV.

I'm against 3 for maintainability.
I think 1 or 2 is fine. Any thoughts on 1 vs 2?

**Comment by nirvdrum** [comment]
I'm of the mind that we shouldn't allow Java exceptions to ever escape for non-interop Ruby code. I don't think we need to make this test pass, I'd just rather see a Ruby exception of some sort. I wouldn't even mind if it were an exception under the `Truffle` namespace. That might even be better because it'd clearly outline to a caller the difference between MRI and TruffleRuby.

I've already solved your first option by updating `jt retag` to retain certain tagged specs, but I haven't opened a PR for that yet.

**Comment by nirvdrum** [comment]
Can we have a global exception handler that wraps the Java exceptions into Ruby ones?

**Comment by eregon** [comment]
> Can we have a global exception handler that wraps the Java exceptions into Ruby ones?

No, that's what we had before and it was a mistake. It's good in general to not catch any internal error and let it be fatal so we can notice it and it's not rescued by some random code. IMO this case just doesn't matter if user code doesn't run into this.
