### ISSUE TITLE
`"hello".force_encoding(Encoding::UTF_16LE)` fails

### ISSUE THREAD

**Issue by postmodern** [oracle/truffleruby#3410]
I noticed a difference in Ruby behavior between CRuby and TruffleRuby. CRuby allows forcibly changing the encoding of an arbitrary UTF-8 String into UTF-16LE. TruffleRuby raises an exception explaining that only Strings a length of a multiple of 2 are supported.

## Steps To Reproduce

```ruby
"hello".force_encoding(Encoding::UTF_16LE)
```

### CRuby

```ruby
"hello".force_encoding(Encoding::UTF_16LE)
# => "\u6568\u6C6C\x6F"
```

### TruffleRuby

```ruby
 "hello".force_encoding(Encoding::UTF_16LE)
(irb):1:in `force_encoding': UTF-16 string byte length is not a multiple of 2 (ArgumentError)
```

## Version Info

* ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
* truffleruby 23.1.2, like ruby 3.2.2, Oracle GraalVM Native [x86_64-linux]

**Comment by eregon** [comment]
This is an expected difference in TruffleRuby.
TruffleString does not support UTF-16 strings (in native endian) with an odd number of bytes.
Same for UTF-32LE and there it needs to be a multiple of 4.
This is necessary for many reasons (compression, optimization, invariants, etc) and it is unlikely to change.

The workaround is easy: either use bytes which are actually meaningful in UTF-16 or at least ensure it's an even number of bytes.

**Comment by postmodern** [comment]
@eregon that is unfortunate. I will either have to somehow rewrite this spec to work around TruffleRuby's lack of UTF-16 support, or drop support for TruffleRuby.
https://github.com/postmodern/fake_io.rb/actions/runs/7654241444/job/20857834421

**Comment by nirvdrum** [comment]
@postmodern Can you please clarify what the use case is? TruffleRuby supports valid UTF-16 and UTF-32 strings. What it doesn't support is declaring an arbitrary sequence of bytes have a UTF-16 or UTF-32 encoding. The whole notion of invalid strings in Ruby is a major design flaw, in my opinion. In all but the most niche of use cases they represent a logic error. Nearly all operations on broken strings are undefined. UTF-16 is also rarely used in Ruby. As I understand it, in general, this is targeting a niche of a niche use case that almost certainly represents a logic error. One that no other high level language allows, for what it's worth.

I don't disagree that it's a compatibility difference. But, what is it affecting? I'm not trying to be glib. I've spent an inordinate amount of time on Ruby strings (in CRuby, JRuby, and TruffleRuby) and encodings. If there's a use case I haven't considered I'd love to update my mental model.

**Comment by postmodern** [comment]
@nirvdrum it's fairly clear based on the spec:
https://github.com/postmodern/fake_io.rb/blob/9f08ce0552a31742b64acf47933d4205d830a7d1/spec/fake_io_spec.rb#L702-L719

When Ruby's `IO#set_encoding_by_bom` is called, it will read the first two bytes and check if they represent a UTF-16 Byte Order Mark (BOM) (aka `"\xFF\xFE"`) and change the external encoding of the IO object if a BOM is detected. Thus my spec tests that the output string is the input string, sans the first two bytes, and that it's encoding is UTF-16LE. The String I am trying to forcibly change the encoding to UTF-16LE is `"hello"`.

> But, what is it affecting?

It's causing TruffleRuby to breaking my CI, which I linked to above. If the CI does not pass under TruffleRuby, then I cannot guarantee that everything will work as expected  under TruffleRuby vs CRuby. Note that the [fake_io](https://github.com/postmodern/fake_io.rb#readme) gem is used by [ronin-post_ex](https://github.com/ronin-rb/ronin-post_ex#readme), which is used by [ronin-payloads](https://github.com/ronin-rb/ronin-payloads#readme) and [ronin-exploits](https://github.com/ronin-rb/ronin-exploits#readme), to provide "fake" IO/File/Socket objects that actually exist on another system but behave *exactly* like real local ones. Note that one of the core pillars of Ronin is maintaining an extremely high standard of quality. Any spec failure under TruffleRuby threatens that high standard of quality.

If TruffleRuby cannot maintain compatibility with CRuby, then I will have to either:

A. Mark the spec as pending when running under TruffleRuby and hope no one submits bug reports to me about this issue.
B. Add a warning or error message to `FakeIO#set_encoding_by_bom` when running under TruffleRuby.
C. Drop support for TruffleRuby until this is resolved.

**Comment by nirvdrum** [comment]
>  it's fairly clear based on the spec

I can see what the spec is doing. I could not work out why it was doing it or what problem it was solving. The spec immediately forces the encoding to `ASCII-8BIT` so the BOM info is promptly discarded. Thank you for the clarification. I didn't realize there was an `IO#set_encoding_by_bom` method.

>  It's causing TruffleRuby to breaking my CI, which I linked to above. If the CI does not pass under TruffleRuby, then I cannot guarantee that everything will work as expected under TruffleRuby vs CRuby.

I think you can guarantee what will happen in this specific case. We error out the `set_encoding_by_bom` call and provide the reason why. What all the following code does will depend on whether and how you handle the exception. I'm not trying to be glib. It's a functional divergence for sure, but it is well-defined.

I appreciate it's breaking your CI and I get that's frustrating. I also truly appreciate your commitment to testing out alternative Ruby implementations like TruffleRuby. Given we don't have 100% compatibility and likely never will for various reasons, there's always something that could fail and in some cases we can't do anything about it. We can't make this work without a fundamental reworking of strings that would then destroy performance. If there's a common use case we've overlooked then that's certainly cause for reevaluation, which is why I was trying to better understand the use case. For what it's worth, the CRuby team also regularly evaluates whether to fix bugs if they adversely impact performance in the dominant case. Granted, they're doing so from a much stronger position.

I may be being dense, but I'm still not sure we're actively blocking progress on anything. You virtually can't do anything  with a broken string except get its bytes and concatenate it with another broken string, hoping the two byte sequences joined produce a new byte sequence. CRuby makes no guarantees at all about operations performed on broken strings. Any code relying on that is subject to break in any future Ruby releases. Most methods them will raise an exception. Many of the others return a non-deterministic result or provides results that violate a method's stated properties. Rather than fail somewhere far removed from the call, in this one particular case we fail early.

There's no doubt you found a hole in our compatibility. I was trying to better understand what you're looking to do with that string. If you don't immediately change the encoding to `ASCII-8BIT`, I don't think there's much you can do with that string that won't raise an exception. I've been advocating for Ruby to reevaluate its handling of broken strings because they're dangerous and error-prone. Most languages won't even construct a broken string because of the problems they lead to.

Ultimately, I can't say what to do with Ronin. All I can emphasize is we're not just being difficult. It'd be quite an undertaking to add that level of compatibility and doing so would slow the handling of valid strings down substantially and increase memory consumption. A build of TruffleRuby with 100% compatibility that runs substantially slower than CRuby has no reason to exist. `IO#set_encoding_by_bom` should work fine with UTF-8 BOMs and valid UTF-16 and UTF-32 BOMs.

There are 100+ encodings in Ruby. All but four of them are ASCII-compatible and those four are the UTF-16 and UTF-32 variants. They're edge cases in CRuby. TruffleRuby will work fine with any of those encodings if there's a valid byte sequence. It will work with a broken byte sequence in all but four cases. It falls short of the platonic ideal, but I don't think it's terrible. I'd be rather surprised if you get a bug report about this, but I'm not terribly active in the security space so I don't know if working with broken UTF-16 documents is a common situation. If it is, then I guess we're stuck.

**Comment by eregon** [comment]
@postmodern I think a very simple solution here is to:
```diff
          "\xFF\xFEhello".force_encoding(Encoding::ASCII_8BIT)
          "\xFF\xFEh\x00e\x00l\x00l\x00o\x00".force_encoding(Encoding::ASCII_8BIT)
```
Which is a valid "hello" in UTF-16.
Or:
```diff
          "\xFF\xFEhello".force_encoding(Encoding::ASCII_8BIT)
          "\xFF\xFEabcd".force_encoding(Encoding::ASCII_8BIT)
```
if it doesn't matter whether those bytes are meaningless in UTF-16.

(`[104, 101, 108, 108, 111]` (ASCII "hello") is meaningless in UTF-16:
`"hello".force_encoding "UTF-16LE" => "\u6568\u6C6C\x6F"` and
`"hello".force_encoding("UTF-16LE").encode "UTF-8" => (irb):4:in 'encode': incomplete "o" on UTF-16LE (Encoding::InvalidByteSequenceError)`)

**Comment by postmodern** [comment]
@eregon that worked, thank you! Although, I suspect I will encounter this again in the future. At least now I know the cause of this error, if/when I spot it again under TruffleRuby.
