### ISSUE TITLE
How to call a method from java whose name is send?

### ISSUE THREAD

**Issue by AlexeyMatskevich** [oracle/truffleruby#3576]
I installed pulsar client on java in my truffleruby-jvm 24.0.1 installation, compiled with Gradle 8.7 and tried to use it (I have absolutely no knowledge of Java and don't know how right I am doing everything).
Here's an example of how I work with a client:
```ruby
Java.add_to_classpath("/app/pulsar-java-client/lib/build/libs/lib-all.jar")
pulsar = Java.type('org.apache.pulsar.client.api.PulsarClient')
client = pulsar.builder.serviceUrl(ENV["PULSAR_URL"]).build

producer = client.newProducer.topic("my-topic").create
```
next step, I try to send a message using the pulsar client documentation as a primary source:
```java
Producer<String> stringProducer = client.newProducer(Schema.STRING)
        .topic("my-topic")
        .create();
stringProducer.send("My message");
```
Unfortunately, I don't understand how I can call the send (java version) method, given the fact that the ruby Object class already defines this method.
Is there any way around this in any way?

**Comment by AlexeyMatskevich** [comment]
This seems to be done as follows
```ruby
producer['send'].call(-> {"My message"})
```

**Comment by eregon** [comment]
This works fine:
```ruby
Dir.glob("pulsar-client/*.jar").each { |f| Java.add_to_classpath File.expand_path f }
pulsar = Java.type('org.apache.pulsar.client.api.PulsarClient')
p pulsar
client = pulsar.builder.serviceUrl("pulsar://localhost:6650/").build
p client

Schema = Java.type('org.apache.pulsar.client.api.Schema')
producer = client.newProducer(Schema.STRING).topic("my-topic").create
p producer

producer[:send].call("My message")
# Or:
Truffle::Interop.invoke_member(producer, :send, "My message")
```

I followed https://pulsar.apache.org/docs/next/getting-started-standalone/ (including running `bin/pulsar standalone`)
and https://pulsar.apache.org/docs/next/client-libraries-java-setup/
and downloaded all Maven jars to a folder with https://stackoverflow.com/a/75183691/388803

So it's `producer[:send].call("My message")` not `producer['send'].call(-> {"My message"})` which would pass a Proc and not a String.
The `Schema.STRING` is also needed otherwise the API seems to expect `[B`, i.e. `byte[]`.
There is also `Truffle::Interop.invoke_member(producer, :send, "My message")` which uses interop explicitly.
